### ISSUE TITLE
Add a safety length to C-interface methods that take a buffer

### ISSUE THREAD

**Issue by Zaerei** [mgbellemare/Arcade-Learning-Environment#110]
As per the discussion in #109, the buffer-taking methods such as getRAM should take in the length of the buffer and throw an exception if the buffer is not of sufficient length. This should be mostly invisible to users of the provided Python wrapper (since the buffer length can be generated automatically), but would be a breaking change for any other FFI wrappers. In most languages it would be trivial to fix, however.

**Comment by mgbellemare** [comment]
@Jragonmiris , do you mean in ale_c_wrapper.h?

**Comment by Jragonmiris** [comment]
It's been a while, but I believe so, yes.

**Comment by mgbellemare** [comment]
Great, thanks.

**Comment by JesseFarebro** [comment]
The new Python interface uses pybind11 and does explicit checks for shape, type, etc.
