### ISSUE TITLE
Inconsistency between Python interface and C++ interface

### ISSUE THREAD

**Issue by mcmachado** [mgbellemare/Arcade-Learning-Environment#111]
The methods `getScreenGrayscale` and `getScreenRGB` are available in the Python interface but they are not available in the C++ interface (`ale_interface.*pp`). I think both interfaces should be consistent.

**Comment by mcmachado** [comment]
I'll suggest a solution today.

**Comment by mgbellemare** [comment]
Fixed by #113.
