### ISSUE TITLE
C interface on OSX doesn't seem to work with SDL

### ISSUE THREAD

**Issue by UserAB1236872** [mgbellemare/Arcade-Learning-Environment#114]
I'm having trouble getting SDL to run via libale_c.so. I've put reference C code and the stack trace in a gist here:

https://gist.github.com/Jragonmiris/b99b5033c52e1ff6d677

This doesn't happen with sharedLibraryInterfaceExample so it's working properly from C++ for some reason. But I can't get the display window to open via any FFI through the C wrapper, whether it's C, Rust, or Python.

USE_SDL is on (obviously, since the C++ example works properly).

I tried explicitly linking with SDL too, with -lsdl and -lsdl2 (just in case), but it didn't seem to help.

**Comment by mhauskn** [comment]
This is a known issue. In the [python example](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/doc/examples/python_example.py), which uses the ale-c-lib, it is necessary to use pygame init to proxy-call SDL_main on OSX. I believe I was getting the same NSConsistency error you describe in the gist. I wasn't able to find a way to fix this, hence the pygame workaround.

**Comment by JesseFarebro** [comment]
This should no longer be an issue with the SDL2 upgrade.
