### ISSUE TITLE
Need instruction on how to contribute to the code and develop compatibility of other games?

### ISSUE THREAD

**Issue by peterzcc** [mgbellemare/Arcade-Learning-Environment#117]
I'm doing a research project on the transfer learning of  DQN using the ale_python_interface. I'm planning to develop the compatibility of other games. It seems like I should add a class in src/games/supported and add it to the "static const RomSettings *roms[]"  in the src/games/roms.cpp. 

Could anyone suggest what else I should do?

Grateful if anyone could help!

Regards,
Peter

**Comment by mgbellemare** [comment]
Hi Peter,

I'll answer the question via the mailing list rather than as a GitHub issue.
