### ISSUE TITLE
ALE for windows 

### ISSUE THREAD

**Issue by rolandbrake** [mgbellemare/Arcade-Learning-Environment#119]
i tried to download ALE on my windows for python but i got this error :error unable to find required library : ale python interface/libale_c.os any help?

**Comment by mgbellemare** [comment]
@mhauskn ?

**Comment by mhauskn** [comment]
Are you building using CMake? Can you verify that "libale_c.so" exists?

**Comment by mgbellemare** [comment]
@RolandBrake , is the issue still present?

**Comment by mcmachado** [comment]
It seems we should close this issue. @mgbellemare, @rolandbrake didn't get back to you, so I assume this is not an issue anymore. What do you say?

**Comment by pedronahum** [comment]
A couple of months ago I managed to compile and test ALE the using cygwin. Would you like me to test the latest release and report back?

**Comment by pedronahum** [comment]
Using cygwin (gcc 6.4.0), there is an issue related to "popen", which is triggered by the c++11 flag (-std=c++11). This affects the "fifoInterfaceExample.cpp" example. 

But replacing -std=c++11 to -std=gnu++11 addresses the issue.  

After making that small change, all the targets are generated in Windows 10.

**Comment by JesseFarebro** [comment]
The ALE can now be compiled on Windows using dependencies provided by vcpkg.
