### ISSUE TITLE
Crash on pacman

### ISSUE THREAD

**Issue by watts4speed** [mgbellemare/Arcade-Learning-Environment#120]
I can repo this using the sharedLibraryInterfaceExample, but it happens in my code also when using ALE.  Download pacman  (4k version), then try and run it.  There's a seg fault.  I saw in the debugger something about Stella.  Sorry I don't have the stack trace right now.  Other games work like pong, breakout, space invaders etc.  A couple games I'm testing with like pacman crash.  I'm on ubuntu.  I have v0.5

**Comment by mcmachado** [comment]
Are you trying to run the game pacman or ms_pacman? We currently only
support the latter.

**Comment by watts4speed** [comment]
Ok that's likely the problem.  I was running original pacman.  Let me try
finding ms_pacman.



On Sun, Dec 13, 2015 at 2:53 AM, Marlos C. Machado <notifications@github.com
> wrote:

> Are you trying to run the game pacman or ms_pacman? We currently only
> support the latter.

**Comment by mgbellemare** [comment]
I'm assuming this issue was sorted out?

**Comment by watts4speed** [comment]
It's been a while, sorry I don't remember. :-(

On Sat, May 14, 2016 at 1:10 PM, Marc G. Bellemare <notifications@github.com
