### ISSUE TITLE
Segfault when starting a second instance with RLGlue

### ISSUE THREAD

**Issue by rubenvereecken** [mgbellemare/Arcade-Learning-Environment#122]
I use RLGlue with ALE and connect a Python experiment and agent with it. Now I have a script that automates the process and was aiming at being able to execute the script multiple times - each time spawning a whole RLGlue-ALE setup. The key to this, I figured, would be to have a different RLGlue port each time so everything could just connect to that and ignore the other setups.

Sadly, my hope was somewhat dented when ALE segfaulted immediately. My immediate guess what that it didn't pick up RLGlue's port properly, then somehow tried to connect to a null port. I dug into the source code and saw it got the port number from `RLGLUE_PORT`, just like RLGlue does. So... dead end for me, and I have been struggling to get this right for some time now.

Would my proposed scenario be possible, or is it somehow not taken into account and not possible? Or if it is possible, what could cause the segfault? I really think it would be valuable to have multiple setups run at the same time.

Edit: Just realized RLGlue says "Environment connected." It crashes right after.

**Comment by mhauskn** [comment]
RLGlue is perhaps the least-tested of the ALE interfaces. If you have a python agent, you may be better off using the native python interface. However, if you really want to stick with the RLGlue interface, please provide a minimum working example that would allow us to replicate the problem.

**Comment by rubenvereecken** [comment]
Alright can do, I think this situation is valuable enough (at least to me) to write some small example that crashes. Sadly, my circumstances require RLGlue, though I use the python interface in another project. 

Thanks, I'll report back later.

**Comment by mgbellemare** [comment]
@rubenvereecken : there shouldn't be anything in the way of running multiple RL-Glue x ALE concurrently, at least from an ALE perspective. Most of the operations are happening inside
rlglue methods. Can you tell trace its behaviour inside the rlGlueLoop?

**Comment by rubenvereecken** [comment]
To be honest, I fail to reproduce this. I fear it may have been an error elsewhere in my code that created some unexpected situation in which ALE segfaults, maybe because it receives data (or a lack thereof) it doesn't expect.

I've currently got two setups running happily next to one another. I'd be happy to close this issue.

**Comment by mgbellemare** [comment]
SGTM. Let us know if it happens again.
