### ISSUE TITLE
Include MD5 or SHA1 checksum for all supported ROM files

### ISSUE THREAD

**Issue by nowozin** [mgbellemare/Arcade-Learning-Environment#123]
Dear developers,

please could you include as a text file in the repository a list of MD5 sums or SHA1 sums of all ROMs currently supported?  For example, you can just run `md5sum *.bin` in your directory of working ROMs to create such a file.

This would make it easier to collect/rename all ROM files.  For example, for some games there are multiple versions (homebrew Tetris for example has the original .a26 version and an updated one, other games have PAL and NTSC versions), and this would make it easy.

Thank you for considering and your excellent work.

Sebastian

**Comment by mgbellemare** [comment]
Yes, that's a good idea. Thanks for the suggestion!

**Comment by nczempin** [comment]
FWIW, someone posted a .zip file of supported roms in the Google Group. Here's my md5sum *.bin of them, not sure if I'd go as far as putting them in the official repository.

- 35be55426c1fec32dfb503b4f0651572  air_raid.bin
- 056f5d886a4e7e6fdd83650554997d0d  amidar.bin
- c31a17942d162b80962cb1f7571cd1d5  assault.bin
- 89a68746eff7f266bbf08de2483abe55  asterix.bin
- ccbd36746ed4525821a8083b0d6d2c2c  asteroids.bin
- 0b33252b680b65001e91a411e56e72e9  atlantis.bin
- 83b8c01c72306d60dd9b753332ebd276  bank_heist.bin
- e434c0e161dd3c3fb435eb6bad2e182c  battle_zone.bin
- 79ab4123a83dc11d468fb2108ea09e2e  beam_rider.bin
- fac28963307b6e85082ccd77c88325e7  berzerk.bin
- c9b7afad3bfd922e006a6bfc1d4f3fe7  bowling.bin
- c3ef5c4653212088eda54dc91d787870  boxing.bin
- f34f08e5eb96e500e851a80be3277a56  breakout.bin
- de29e46dbea003c3c09c892d668b9413  carnival.bin
- 17d000a2882f9fdaa8b4a391ad367f00  centipede.bin
- c1cb228470a87beb5f36e90ac745da26  chopper_command.bin
- 55ef7b65066428367844342ed59f956c  crazy_climber.bin
- e1029676edb3d35b76ca943da7434da8  defender.bin
- b24f6a5820a4b7763a3d547e3e07441d  demon_attack.bin
- cfc226d04d7490b69e155abd7741e98c  double_dunk.bin
- 71f8bacfbdca019113f3f0801849057e  elevator_action.bin
- 94b92a882f6dbaa6993a46e2dcc58402  enduro.bin
- b8865f05676e64f3bec72b9defdacfa7  fishing_derby.bin
- 8e0ab801b1705a740b476b7f588c6d16  freeway.bin
- 4ca73eb959299471788f0b685c3ba0b5  frostbite.bin
- 8f90590dba143d783df5a6cff2000e4d  gopher.bin
- 4767356fa0ed3ebe21437b4473d4ee28  gravitar.bin
- fca4a5be1251927027f2c24774a02160  hero.bin
- 47711c44723da5d67047990157dcb5dd  ice_hockey.bin
- e51030251e440cffaab1ac63438b44ae  jamesbond.bin
- 718ae62c70af4e5fd8e932fee216948a  journey_escape.bin
- 4326edb70ff20d0ee5ba58fa5cb09d60  kangaroo.bin
- cc724ebe74a109e39c0b2784ddc980ca  krull.bin
- 0b4e793c9425175498f5a65a3e960086  kung_fu_master.bin
- 3347a6dd59049b15a38394aa2dafa585  montezuma_revenge.bin
- 9469d18238345d87768e8965f9f4a6b2  ms_pacman.bin
- f98d2276d4a25b286135566255aea9d0  name_this_game.bin
- 7e52a95074a66640fcfde124fffd491a  phoenix.bin
- f73d2d0eff548e8fc66996f27acf2b4b  pitfall.bin
- 60e0ea3cbe0913d39803477945e9e5ec  pong.bin
- 668dc528b7ea9345140f4fcfbecf7066  pooyan.bin
- ef3a4f64b6494ba770862768caf04b86  private_eye.bin
- 484b0076816a104875e00467d431c2d2  qbert.bin
- da5096000db5fdaa8d02db57d9367998  riverraid.bin
- 7d3cdde63b16fa637c4484e716839c94  road_runner.bin
- 4f618c2429138e0280969193ed6c107e  robotank.bin
- f1a0a23e6464d954e3a9579c4ccd01c8  save_alien.bin
- 240bfbac5163af4df5ae713985386f92  seaquest.bin
- 367411b78119299234772c08df10e134  skiing.bin
- e72eb8d4410152bdcb69e7fba327b420  solaris.bin
- 61dbe94f110f30ca4ec524ae5ce2d026  space_invaders.bin
- a3c1c70024d7aabb41381adbfb6d3b25  star_gunner.bin
- a5c96b046d5f8b7c96daaa12f925bef8  tennis.bin
- fc2104dd2dadf9a6176c1c1c8f87ced9  time_pilot.bin
- 66c2380c71709efa7b166621e5bb4558  tutankham.bin
- a499d720e7ee35c62424de882a3351b6  up_n_down.bin
- c63a98ca404aa5ee9fcff1de488c3f43  venture.bin
- a2424c1a0c783d7585d701b1c71b5fdc  video_pinball.bin
- 663ef22eb399504d5204c543b8a86bcd  wizard_of_wor.bin
- ee8027d554d14c8d0b86f94737d2fdcc  yars_revenge.bin
- eea0da9b987d661264cce69a7c13c3bd  zaxxon.bin

**Comment by nczempin** [comment]
and

`<plug>` 
- 5428cdfada281c569c74c7308c7f2c26  Kaboom! (Paddle) (1981) (Activision, Larry Kaplan, David Crane)(AG-010, AG-010-04) ~.bin

`</plug>`
