### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by xgdgsc** [mgbellemare/Arcade-Learning-Environment#139]
Currently I have to modify the print function in setup.py to install, I haven' t tested whether it can be used with python 3. Is there python 3 support for now?

**Comment by pierrelux** [comment]
Yes beside that, just make sure to prefix the setting strings with "b". For example: ``ale.setBool(b'color_averaging', True)``

**Comment by bbitmaster** [comment]
In addition, I could not get the ale_python_interface to install using setup.py in python 3. It seemed to install, but the symbols were missing from the import. The fix was to change the __init__.py file to contain:
`
from ale_python_interface.ale_python_interface import *
`

**Comment by mgbellemare** [comment]
@mhauskn , can you weigh in?

**Comment by pierrelux** [comment]
@bbitmaster I run my code with ```from ale_python_interface import ale_python_interface as ALE```

**Comment by mhauskn** [comment]
@mgbellemare I haven't gotten around to testing/building with Python 3 yet. It's definitely something ALE should support so, I'd be happy to look into it over the next few days.

**Comment by marcgb** [comment]
@xgdgsc @mhauskn does pull request #145 address this issue?

**Comment by mhauskn** [comment]
Yes, it does.

**Comment by mgbellemare** [comment]
Fixed by #145.
