### ISSUE TITLE
160 x 250 rather than 160 x 210

### ISSUE THREAD

**Issue by pierrelux** [mgbellemare/Arcade-Learning-Environment#140]
The JAIR paper mentions 160 x 210 for the screen size. However, with the ALE version from Github ( 1caf33a3743914e71bdce4a6f9409fac66b91b88), it seems that all screens sizes are 160 x 250 pixels. 

This seems to be coming from line 217 of ``src/emucore/Console.cxx``.

**Comment by pierrelux** [comment]
Some ROMs exist in PAL rather than NTSC format. It seems that NTSC maps to 250 while PAL is 210.

**Comment by mgbellemare** [comment]
What was the conclusion?

**Comment by pierrelux** [comment]
Probably not a bug, but you need to pay attention to the kind of ROMs you're downloading: it seems that you want NTSC, not PAL.
