### ISSUE TITLE
All 3 GetScreen functions return a frame that's averaged with the last one

### ISSUE THREAD

**Issue by jeanharb** [mgbellemare/Arcade-Learning-Environment#141]
Hey guys,

I'm not sure if it's supposed to be like this, but using ale_python_inferface's getScreenGrayscale I get the following image in breakout. You can see that the paddle is averaged out from its movement. I also get the same effect from getScreen and getScreenRGB. In pong, both paddles had the effect.
![breakout_frame](https://cloud.githubusercontent.com/assets/2679003/12660686/f42618f6-c5e2-11e5-8109-2246f5923e48.png)

Thanks,
Jean

**Comment by jeanharb** [comment]
Just found the flag. In the manual, it says that -color_averaging is set to False by default, but it seems to be set to True.

**Comment by pierrelux** [comment]
@jeanharb It seems that the doc should be updated then !
