### ISSUE TITLE
No emulation on no-op or redundant action

### ISSUE THREAD

**Issue by RasmooL** [mgbellemare/Arcade-Learning-Environment#154]
When executing certain actions such as no-op or moving into a wall on Breakout, the emulation doesn't progress (e.g. the ball never spawns on Breakout).

A minimal example is as follows.

```
from ale_python_interface import ALEInterface
import cv2

cv2.startWindowThread()
cv2.namedWindow('atari')

ale = ALEInterface()
ale.loadROM('breakout.bin')
while not ale.game_over():
    screen = ale.getScreenRGB()
    cv2.imshow('atari', screen)

    ale.act(0) # noop
```

**Comment by mgbellemare** [comment]
Hi @RasmooL , in Breakout the ball will not come down until 'fire' is pressed. Did you try adding ale.act(1) (1 should be the 'fire' action)?

**Comment by RasmooL** [comment]
Well that was resolved easily, sorry for the bother :)
