### ISSUE TITLE
ALE_python_interface stuck when running simutaneously in multiple threads

### ISSUE THREAD

**Issue by peterzcc** [mgbellemare/Arcade-Learning-Environment#156]
I'm trying to run 16 ALE_python_interface instances in parallel and run the games simultaneously using concurrent.futures.ProcessPoolExecutor.map

However, I got stuck when calling ale.act(action) in the subprocesses. 

It takes 0.27 seconds to run 16 ALE instances sequentially, which is too long.

Could anyone help to make some suggestions? Thanks!

**Comment by mgbellemare** [comment]
Hi,

What do you mean by "got stuck", exactly? There shouldn't be any locking
involved here.

Also, ALE is close to, but possibly not quite thread-safe.

Cheers,
- Marc

**Comment by peterzcc** [comment]
Hi Marc,

Thanks for your comment.
I solved the issue using concurrent.futures.ThreadPoolExecutor.

Cheers,
Peter
