### ISSUE TITLE
Checkpoints from human play

### ISSUE THREAD

**Issue by ionelhosu** [mgbellemare/Arcade-Learning-Environment#163]
I'm trying to implement the "human starts" evaluation metric described in the latest DQN paper from this year's ICLR  [http://arxiv.org/abs/1511.05952]. For this, I have to generate and save checkpoints in the environment at different times, as I'm controlling the agent from the keyboard. I'm having a hard time doing this, as I have to modify the core functionalities of the emulator. Is there an easy way to do this that I'm not getting? Thank you very much!

**Comment by mgbellemare** [comment]
I'm assuming you mean you want to load the same human starts as used in that paper? The human starts code is specific to the DeepMind fork of the ALE, Xitari:

https://github.com/deepmind/xitari

The ALE solution to the same problem is to use a small amount of action stochasticity (introduced in version 0.5). If you really want to load the human starts in ALE, it should be possible to use cloneState/restoreState() in ALEInterface, but there might be some conversion involved.

**Comment by ionelhosu** [comment]
Thank you very much for your answer, sir. I already managed to use cloneState/restoreState() together with encoldeState/decodeState() to generate and restore checkpoints in ALE, but the truth is I was interested in doing it in Torch, with Xitari/Alewrap, because I write my networks in Torch. The problem is that I didn't manage to control the agent from the keyboard with alewrap/Xitari. 

I also thought about using ALE to generate the checkpoints and load them alewrap/Xitari, but the states seem to be incompatible.

**Comment by mgbellemare** [comment]
Xitari and ALE should be doing similar things. You could try using Xitari's ArchiveBinaryIn/Out instead of ALE's serialization (which is really Stella's). But as you point out, there's no ready-made solution, unfortunately.
