### ISSUE TITLE
System state not being restored deterministically

### ISSUE THREAD

**Issue by rhaps0dy** [mgbellemare/Arcade-Learning-Environment#165]
This code fails the assertions, unless both `act_1` and `act_2` are `PLAYER_A_NOOP`. The assertions test whether the emulation result is the same before and after restoring to a saved state.

It also fails the assertions if `cloneState` and `restoreState` are used.

``` c++
#include <ale_interface.hpp>
#include <cassert>

int main(int argc, char *argv[]) {
    ALEInterface ale;
    byte_t arr[0x80];

    ale.setInt("random_seed", 1234);
    ale.setBool("display_screen", true);
    ale.setBool("sound", false);
    ale.setInt("fragsize", 64);
    ale.loadROM("/path/to/montezuma_revenge.bin");

    const Action act_1 = PLAYER_A_LEFT;
//  const Action act_1 = PLAYER_A_NOOP;
    const Action act_2 = PLAYER_A_LEFT;
//  const Action act_2 = PLAYER_A_NOOP;

    while(!ale.game_over()) {
        ALEState s = ale.cloneSystemState();
//      ALEState s = ale.cloneState();
        ale.act(act_1);
        for(int i=0; i<0x80; i++)
            arr[i] = ale.getRAM().get(i);
        ale.act(act_2);

        ale.restoreSystemState(s);
//      ale.restoreState(s);
        ale.act(act_1);
        for(int i=0; i<0x80; i++)
            assert(arr[i] == ale.getRAM().get(i));
        ale.act(act_2); // unnecessary but symmetry is pretty
    }
    return 0;
}
```

**Comment by rhaps0dy** [comment]
Adding `ale.setFloat("repeat_action_probability", 0)` fixes it.
This is slightly embarrassing, but leaving it up for other confused people in the future.

**Comment by mgbellemare** [comment]
Glad this was easily fixed :) I think the ALE stochasticity option needs more visibility, maybe in `README.md`. Will create an issue.

**Comment by mgbellemare** [comment]
Okay, I see the problem now. When `restoreSystemState()` is called the environment's `ALERAM` and `ALEScreen` objects are not refreshed. It's possible to restore the first, but not the second (because the screen isn't serialized, since it isn't stored anywhere on the Atari 2600 hardware). This certainly needs to generate a warning.

My recommendation is to use a 'dirty' flag that throws an assert when calling getScreen() immediately after a call to restoreSystemState (i.e. without intervening act()). We can document this in the manual/FAQ. When calling getRAM() the same flag can call processRAM(), which will properly refresh the ALERAM object.

Let me know if you want to take care of this, otherwise I will get around to it within the week.

**Comment by rhaps0dy** [comment]
Yes, I can take care of this. Here is another related possible problem.

```c++
#include <ale_interface.hpp>

int main(int argc, char *argv[]) {
    ALEInterface ale;
    ale.setBool("display_screen", true);
    ale.loadROM("/path/to/montezuma_revenge.bin");

    // Remove the default display_screen after each action
    DisplayScreen *display = ale.theOSystem->p_display_screen;
    ale.theOSystem->p_display_screen = NULL;

    while(!ale.game_over()) {
        ALEState s = ale.cloneState();
        ale.act(PLAYER_A_FIRE);
        ale.restoreState(s);
        ale.act(PLAYER_A_NOOP);
        display->display_screen();
    }
    return 0;
}
```

The character jumps when using `restoreState`, and stays still when using `restoreSystemState`. Is this intended behavior?

**Comment by shelhamer** [comment]
I am likewise interested in addressing this as my research requires restoring trajectories.

> My recommendation is to use a 'dirty' flag that throws an assert when calling getScreen() immediately after a call to restoreSystemState (i.e. without intervening act()). We can document this in the manual/FAQ. When calling getRAM() the same flag can call processRAM(), which will properly refresh the ALERAM object.

Is there any harm in calling `processRAM()` from the `restoreState()` and `restoreSystemState()` methods? I'm sorry if that should be obvious—I'm still orienting myself in the ALE code.

> [it's not possible to restore the screen] (because the screen isn't serialized, since it isn't stored anywhere on the Atari 2600 hardware).

For now I have been advancing the emulator one step by a recorded action (in essence restoring the following state), but I was hoping I could address this directly. Having restored the RAM state, is there no way to regenerate the screen contents?

As an aside, when `color_averaging` is true two steps are required to avoid glitchy observations.

**Comment by mgbellemare** [comment]
@rhaps0dy That also shouldn't be happening. I'll look into it tomorrow.

No harm in calling `processRAM()` (except for slightly slower restore speeds), but we can't easily do the same for the screen. There's no framebuffer in the Atari -- the screen is actually generated on the fly, during the emulation step.

My solution when I was recording trajectories was exactly yours, which is to restore the state just prior to the state I cared about. It's not very elegant. A better solution is to package the ALEState and the ALEScreen together and serialize those. I wouldn't change the current ALEState serialization itself though, for efficiency reasons.

**Comment by rhaps0dy** [comment]
Do you know why this happens yet, @mgbellemare ? I've looked a little into it and I have no clue, the emulator gets restored in exactly the same way.

**Comment by mgbellemare** [comment]
I'm assuming this issue is no longer relevant, closing.
