### ISSUE TITLE
Add support to game Surround

### ISSUE THREAD

**Issue by mcmachado** [mgbellemare/Arcade-Learning-Environment#172]
Some papers from DeepMind report results in the game Surround. We currently don't support this game.

**Comment by nczempin** [comment]
the title should say "game Surround", not "game Support"

**Comment by nczempin** [comment]
Oh, look what I found:
https://github.com/deepmind/xitari/blob/master/games/supported/Surround.cpp
https://github.com/deepmind/xitari/blob/master/games/supported/Surround.hpp

Adding it to ALE needs some additions to some other files, see what I did for my [Kaboom! add](https://github.com/mgbellemare/Arcade-Learning-Environment/pull/190)

**Comment by justinkterry** [comment]
Has anything happened with this? I'd really like use surround for a project I'm working on.

**Comment by danijar** [comment]
Would be great if this could be added to allow comparison on the Atari57 benchmark used by most DeepMind papers.

**Comment by justinkterry** [comment]
This issue was close by #327
