### ISSUE TITLE
Minimal action set is wrong

### ISSUE THREAD

**Issue by rubenvereecken** [mgbellemare/Arcade-Learning-Environment#179]
When trying the ROM Video Game Olympics on ALE 0.5.1, I get the wrong action set. In fact, I get the action set for Space Invaders, another game I use frequently. 

I verified it indeed runs the ROM I intended it to:

```
  Cart Name: Video Olympics (1978) (Atari)
```

The reported actions are `[ 0  1  3  4 11 12]`, which should really just be `[ 0 3 4]` which I do get on another machine on ALE 0.5.0.

**Comment by mgbellemare** [comment]
The fire button is in fact used in Video Game Olympics ('pong.bin'), hence the three extra actions. See manual at

`https://atariage.com/software_page.html?SoftwareID=1434`

**Comment by rubenvereecken** [comment]
Huh, cool, thanks for that. So what makes my other and older ALE detect the wrong action set? Either way, I guess it's probably fixed in the newer version. If so, this can be closed.

**Comment by mgbellemare** [comment]
Yes, this is a fairly recent fix. You don't need the fire button for perfect play in the deterministic version, hence the oversight.
