### ISSUE TITLE
How can I get sound output as data just like function getScreenRGB ?

### ISSUE THREAD

**Issue by boluoweifenda** [mgbellemare/Arcade-Learning-Environment#183]
I want to use both image and sound data to analyze agent's state,
I noticed that SDL support in ALE can output sound to mic and record a wav file, but It's arduous to extract.
Is there any way to get sound data directly from the emulator?

**Comment by mgbellemare** [comment]
This isn't supported at the moment. If this is something you'd like to contribute, I'd be happy to help you get started -- email or PM me.

**Comment by hholst80** [comment]
Just want to keep myself in the loop if something happens here. ALE would be a good test bed for graphics and audio input to agents.

**Comment by JesseFarebro** [comment]
PR #233 introduces the ability to query the audio samples. I might have more time to refine #233 in the future but as of right now people can use @shayegano's fork with audio support.
