### ISSUE TITLE
Wrong screen size with getScreenRGB and Python

### ISSUE THREAD

**Issue by svepe** [mgbellemare/Arcade-Learning-Environment#185]
The image returned from `getScreenRGB()` with the Python interface has a resolution `160x210` (width x height), i.e. it is in portrait, while the image drawn in the SDL display is in landscape. I have confirmed the issue with a few games, so I do not think it is ROM related. I tried digging around the code a bit, but couldn't figure it out. I am happy to fix it as long as anybody has an idea why this is the case.

**Comment by mgbellemare** [comment]
Svetlin,

The native resolution at which Atari images is actually 160x210 (some games
have taller screens). This is typically stretched out to be wider than
large, either in 4:3 or 2:1. The 160 "pixels" width comes from the image
not consisting of pixels at all, but rather scanlines. Put another way,
Atari pixels do not correspond to squares but instead rectangles.

Best,
- Marc

**Comment by svepe** [comment]
Marc,

I see. Thanks for the info.

- Svet
