### ISSUE TITLE
allow ctype buffer input to getScreen

### ISSUE THREAD

**Issue by astooke** [mgbellemare/Arcade-Learning-Environment#189]
Hi,
  A simple suggestion is to allow `getScreen()`, `getScreenRGB()`, `getScreenGrayscale()`, and `getRAM()`  to receive a buffer that is already a ctype.  Currently, providing the a numpy buffer doesn't seem to save much time, because the call to `as_ctypes()` is always there and is more time consuming than the numpy allocation.  Could add a kwarg like `ctype_buf`.  And would recommend returning the passed-in ctype object without forcing a `numpy.asarray()` call on it.  Just a little speed tweak :)

**Comment by JesseFarebro** [comment]
There's now a new Python interface that uses pybind11. It utilizes pybind11's `py::array` type so users can provide NumPy arrays so we can do some explicit checks for shape, type, etc. Your optimization suggestion should be handled behind the scenes now.
