### ISSUE TITLE
Read score (reward) from the screen, not from reverse-engineered RAM values

### ISSUE THREAD

**Issue by nczempin** [mgbellemare/Arcade-Learning-Environment#192]
Adding a ROM to ALE is a non-trivial process, one part of which consists of mapping the game's score to places in memory, and it requires recompiling the C++ code.

Humans don't need to look at RAM to know the score, it's right there on the screen.

Although I am not an AI researcher, I'm fairly sure that recognizing artificially created digits is a fairly simple issue, especially given the nature of the community that uses ALE (i. e. you guys know how to do it).

While it is of course possible for any agent to do the digit recognition by themselves, it would be convenient if ALE could provide

1. coordinates where the score is found on the screen, for a list of predefined ROMs (this list could easily be a text file so nothing would have to be recompiled, and these coordinates could be collected by non-experts.
2. a way for ALE to automatically extract the digits from these coordinates and turn that into the score.

ROMs that need more special treatment are free to keep using C++ code, but I feel that a vast number of ROMs could be added to the environment by this method.

The other thing that is missing is the minimal actions, but that should be data-driven rather than code anyway. So initially a bunch of ROMs could be added that would just have a score and no minimal actions, but IMHO that wouldn't be a big deal.

**Comment by mgbellemare** [comment]
@nczempin , this sounds like an interesting AI project -- it probably wouldn't be too hard, as you say, with current technology. On the other hand, it doesn't seem worth the added compute cost (it would probably add a significant parsing overhead), and error potential.

Regarding minimal actions: I'm not a big fan myself, as good agents don't need them. It'd be interesting to write a program to detect which actions are "minimal" -- maybe using some of our earlier work on [contingency awareness](http://www.marcgbellemare.info/static/publications/bellemare12investigating.pdf)?

**Comment by nczempin** [comment]
BTW it turns out that openai-universe already does something like this; see [Universe](https://blog.openai.com/universe/), scroll down to "Extracting rewards."
