### ISSUE TITLE
getScreenRGB resizes a vector three times larger than needed

### ISSUE THREAD

**Issue by dudevil** [mgbellemare/Arcade-Learning-Environment#203]
Hi,

When calling `getScreenRGB` the `output_rgb_buffer` vector size is multiplied by 3 two times:
Once when calling `applyPaletteRGB` [here](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/ale_interface.cpp#L274) 
and the second time inside the `applyPaletteRGB` function [here](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/common/ColourPalette.cpp#L89).
The vector then gets resized, which could cause trouble to anyone trying to copy it with `std:copy_n` for example.

**Comment by mgbellemare** [comment]
Fixed by #205 .
