### ISSUE TITLE
Cannot find -lSDL and -lSDLmain on Red Hat Enterprise Linux Server release 7.3 

### ISSUE THREAD

**Issue by regularNN** [mgbellemare/Arcade-Learning-Environment#208]
I tried to install ALE in a RedHat 7 machine on which I do not have root access. cmake command outputs the following :
$ cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=OFF  ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found SDL: /usr/lib/libSDLmain.a;/usr/lib/libSDL.so;-lpthread (found version "1.2.15")
CMake Warning (dev) at CMakeLists.txt:215 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
    IF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
      MESSAGE(FATAL_ERROR \"Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
    ENDIF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")

    FILE(READ \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\" files)
    STRING(REGEX REPLACE \"\\n\" \";\" files \"\${files}\")
    FOREACH(file \${files})
      MESSAGE(STATUS \"Uninstalling \"\$ENV{DESTDIR}\${file}\"\")
      IF(EXISTS \"\$ENV{DESTDIR}\${file}\")
        EXEC_PROGRAM(
          \"@CMAKE_COMMAND@\" ARGS \"-E remove \"\$ENV{DESTDIR}\${file}\"\"
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT \"\${rm_retval}\" STREQUAL 0)
          MESSAGE(FATAL_ERROR \"Problem when removing \"\$ENV{DESTDIR}\${file}\"\")
        ENDIF(NOT \"\${rm_retval}\" STREQUAL 0)
      ELSE(EXISTS \"\$ENV{DESTDIR}\${file}\")
        MESSAGE(STATUS \"File \"\$ENV{DESTDIR}\${file}\" does not exist.\")
      ENDIF(EXISTS \"\$ENV{DESTDIR}\${file}\")
    ENDFOREACH(file)
    '

  the old evaluation rules produce:

    '
    IF(NOT EXISTS "/home/installs/gym/Arcade-Learning-Environment/build/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: /home/installs/gym/Arcade-Learning-Environment/build/install_manifest.txt")
    ENDIF(NOT EXISTS "/home/installs/gym/Arcade-Learning-Environment/build/install_manifest.txt")

    FILE(READ "/home/installs/gym/Arcade-Learning-Environment/build/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "/usr/local/bin/cmake" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  but the new evaluation rules produce:

    '
    IF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
    ENDIF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")

    FILE(READ "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "@CMAKE_COMMAND@" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/installs/gym/Arcade-Learning-Environment/build

**Then I run make command and its output is**:

 $ make
 Scanning dependencies of target ale-c-lib
 [  0%] Linking CXX shared library ../ale_python_interface/libale_c.so
 /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libSDLmain.a when 
 searching for -lSDLmain
 /usr/bin/ld: skipping incompatible /lib/libSDLmain.a when searching for -lSDLmain
 /usr/bin/ld: skipping incompatible /usr/lib/libSDLmain.a when searching for -lSDLmain
 /usr/bin/ld: cannot find -lSDLmain
 /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libSDL.so when searching for -lSDL
 /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libSDL.a when searching for -lSDL
 /usr/bin/ld: skipping incompatible /lib/libSDL.so when searching for -lSDL
 /usr/bin/ld: skipping incompatible /lib/libSDL.a when searching for -lSDL
 /usr/bin/ld: skipping incompatible /usr/lib/libSDL.so when searching for -lSDL
 /usr/bin/ld: skipping incompatible /usr/lib/libSDL.a when searching for -lSDL
 /usr/bin/ld: cannot find -lSDL
 collect2: error: ld returned 1 exit status 
 make[2]: *** [../ale_python_interface/libale_c.so] Error 1
 make[1]: *** [CMakeFiles/ale-c-lib.dir/all] Error 2
 make: *** [all] Error 2

**I read somewhere to include this for troubleshooting. So here is the output of `locate libSDL` command:**

 $ locate libSDL 
  /usr/lib/libSDL-1.2.so.0
  /usr/lib/libSDL-1.2.so.0.11.4
  /usr/lib/libSDL.a
  /usr/lib/libSDL.la
  /usr/lib/libSDL.so
  /usr/lib/libSDLmain.a
  /usr/lib/libSDLmain.la
  /usr/lib64/libSDL-1.2.so.0
  /usr/lib64/libSDL-1.2.so.0.11.4
  /usr/local/MATLAB/R2017a/bin/glnxa64/libSDL2-2.0.so.0.2.1
  /usr/local/MATLAB/R2017a/bin/glnxa64/libSDL2-2.0.so.1
  /usr/local/MATLAB/R2017a/bin/glnxa64/libSDL2.so

**Though I have specifically asked my administrator to install  SDL-devel-1.2.15-1.i386.rpm. Here is the output that he provided me of installation of SDL devel:**

 Installing : SDL-1.2.15-14.el7.i686                                                                                                                              1/2
  Installing : SDL-devel-1.2.15-1.i386                                                                                                                             2/2
rhel-7-server-rpms/7Server/x86_64/productid                                                                                                     | 2.1 kB  00:00:00
  Verifying  : SDL-devel-1.2.15-1.i386                                                                                                                             1/2
  Verifying  : SDL-1.2.15-14.el7.i686                                                                                                                              2/2
Installed:
  SDL-devel.i386 0:1.2.15-1
Dependency Installed:
  SDL.i686 0:1.2.15-14.el7
Complete!

**I do not understand what is wrong here. Can you please help. 
Thanks !**

**Comment by mgbellemare** [comment]
Hi,

It looks like you have both SDL2 and SDL1.2 installed -- ALE uses 1.2. Did
you check that the symlinks libSDL.so, libSDL.a are all consistent -- i.e.
point to the same version? If you ls -l these files it should provide a bit
more information.

**Comment by regularNN** [comment]
Yes thats true, we have both versions installed. Here is the output of `ls -l` command: 
```
(tf2) [rgupta.cse@compute-01 installs]$ ls -l /usr/lib/libSDL.a  
-rw-r--r-- 1 root root 658224 Jan 19  2012 /usr/lib/libSDL.a 
(tf2) [rgupta.cse@compute-01 installs]$ ls -l /usr/lib/libSDL.so 
lrwxrwxrwx 1 root root 20 Aug  5 11:18 /usr/lib/libSDL.so -> libSDL-1.2.so.0.11.4
```

**Comment by regularNN** [comment]
You are right. This is the culprit I think. Below are the desired outputs:
```
$ file /usr/lib/libSDL.a
/usr/lib/libSDL.a: current ar archive
$ file /usr/lib/libSDL.so
/usr/lib/libSDL.so: symbolic link to `libSDL-1.2.so.0.11.4'
$ file /usr/lib/libSDL-1.2.so.0.11.4
/usr/lib/libSDL-1.2.so.0.11.4: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=dacd666b0f645eeccc77dafa1fbfff804067fb8b, stripped
```
As libSDL is 32-bit shared object. Where as when I compile with DUSE_SDL=OFF, then it turns out to be 64 bit. As you can see:
```
$ file ale
ale: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=8c198914f97f8f99b960055d82fed96ef2976f99, not stripped
```
But I already have libSDL 64 bit in my system, in other location. 
```
$ file /usr/lib64/libSDL-1.2.so.0.11.4
/usr/lib64/libSDL-1.2.so.0.11.4: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7c350725e2a0cac6b0e1b32fd5764e0921140f30, stripped
```
How can I force it to use this location i.e. `/usr/lib64/`,  instead of `/usr/lib/` ?

**Comment by mgbellemare** [comment]
You should be able to force the path in the CMake -- take a look at
CMakeLists.txt around the call to find_package(SDL).

**Comment by regularNN** [comment]
Thank you very much. Finally I am able to install it. I inserted a line `set(SDL_LIBRARY /usr/lib64/libSDL-1.2.so.0)` after `find_package(SDL)` in CMakeLists.txt and it did the trick.
