### ISSUE TITLE
AirRaid is throwing an exception

### ISSUE THREAD

**Issue by mcmachado** [mgbellemare/Arcade-Learning-Environment#219]
When running:

`doc/examples/ale-sharedLibraryInterfaceExample ~/roms/air_raid.bin`

I get the following error:

`Assertion failed: ((val & 0x01) == 0), function getRGB, file /Users/marlos.c.machado/Arcade-Learning-Environment/src/common/ColourPalette.cpp, line 51.`

**Comment by mgbellemare** [comment]
Closing -- see #195 .
