### ISSUE TITLE
Can't install python interface through pip on dev branch

### ISSUE THREAD

**Issue by renattou** [mgbellemare/Arcade-Learning-Environment#221]
Using the current dev branch, I can perform the compilation steps with no problem and the "libale_c.so" file is being generated. But when I try to run "pip install --user .", I get some compilation errors.

At first I get:
> In file included from src/games/RomSettings.hpp:42:0,
>                      from src/games/Roms.hpp:15,
>                      from src/ale_interface.hpp:39,
>                      from ale_python_interface/ale_c_wrapper.h:4,
>                      from ale_python_interface/ale_c_wrapper.cpp:1:
>     src/games/../environment/stella_environment_wrapper.hpp:20:23: fatal error: Constants.h: No such file or directory

Changing this line to "#include "../common/Constants.h" fix this error, but gives a whole lot of others. Mainly errors related to "std::unique_ptr", like:
> In file included from src/games/Roms.hpp:15:0,
>                      from src/ale_interface.hpp:39,
>                      from ale_python_interface/ale_c_wrapper.h:4,
>                      from ale_python_interface/ale_c_wrapper.cpp:1:
>     src/games/RomSettings.hpp:104:31: error: ‘std::unique_ptr’ has not been declared
>                               std::unique_ptr\<StellaEnvironmentWrapper\> environment);

I thought that actually after compiling with make, it wouldn't be necessary to compile again, so this is odd. Also, on the master branch, everything goes smoothly. Any ideas?

**Comment by mgbellemare** [comment]
The Constants.h error is a genuine bug -- can you submit a fix?

Regarding std::unique_ptr: it's a C++11 feature. Your compiler should be compiling with C++11.  You say this is happening when you run pip install, or when you compile the project?

**Comment by renattou** [comment]
I submitted the fix you asked and actually already fix this issue by forcing pip to use C++11 on setup.py.

**Comment by renattou** [comment]
Closing this as it was fixed with the merged PR.
