### ISSUE TITLE
How to retrieve level in games with multiple levels? Auto-start inconsistencies?

### ISSUE THREAD

**Issue by gabrieledcjr** [mgbellemare/Arcade-Learning-Environment#223]
- Is there a function that can retrieve the current level in multi-level games (e.g. BeamRider, etc)
- Is this a design choice as to why other games require a certain action to start while other games just start automatically? Pong starts automatically, while Breakout requires a certain action to start the game. Also games like BeamRider, when you reach a new level or when losing a life, you also have to use a certain action just to continue playing the game.

**Comment by mgbellemare** [comment]
Thanks for your question!

- The founding principle behind the ALE is to provide an interface which is as close as possible to the original game. Different games have different interfaces, hence the variety.
- Hence no, there isn't a function to retrieve levels. FWIW we probably wouldn't support it either.
