### ISSUE TITLE
ALE thread safe?

### ISSUE THREAD

**Issue by jph11** [mgbellemare/Arcade-Learning-Environment#239]
Hello! I'd like to ask if ALE is already thread-safe and if it's possible to instantiate the ALE interface in more than just one thread.

Thanks in advance!

**Comment by mgbellemare** [comment]
Hi,

I believe there's a few things that aren't thread-safe in the current version. An alternative is to look at Xitari, which was made thread-safe:

https://github.com/deepmind/xitari
