### ISSUE TITLE
error in the step “make -j 4”

### ISSUE THREAD

**Issue by timelong** [mgbellemare/Arcade-Learning-Environment#240]
after “make -j 4”，error1: recipe for target “CMakefiles/ale-clib.dir/src/common/._ScreenExporter.cpp.o” failed

error2: recipe for target ‘CMakefiles/ale-c-lib.dir/all’ failed

How shoule I solve this problem？Please！

**Comment by mgbellemare** [comment]
I'm afraid I haven't seen this error before -- do you get it when building from scratch?

**Comment by willtop** [comment]
Hello same issue here! I am wondering how did you end up solving this? Thanks!
