### ISSUE TITLE
Can't build in macOS

### ISSUE THREAD

**Issue by ustcJin** [mgbellemare/Arcade-Learning-Environment#241]
cp makefile.os makefile && make ; 

Get following error

OS:10.12.2

"Undefined symbols for architecture x86_64:
  "buildRomRLWrapper(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      ALEInterface::loadROM(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in ale_interface.o
      ALEController::ALEController(OSystem*) in ale_controller.o
  "Serializer::putString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      ALEState::serialize[abi:cxx11]() in ale_state.o
...
  "virtual thunk to std::__1::basic_iostream<char, std::__1::char_traits<char> >::~basic_iostream()", referenced from:
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in Deserializer.o
      construction vtable for std::__1::basic_iostream<char, std::__1::char_traits<char> >-in-std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> > in Serializer.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [ale] Error 1

**Comment by ustcJin** [comment]
compile line is 
g++-6 -Wp,-MMD,"src/external/TinyMT/.deps/tinymt32.d",-MQ,"src/external/TinyMT/tinymt32.o",-MP  -Wall -Wunused -fPIC -O3 -fomit-frame-pointer -DRLGENV_NOMAINLOOP -DUNIX -DHAS_ALTIVEC -DUSE_NASM -DBSPF_UNIX -DHAVE_INTTYPES -DWINDOWED_SUPPORT  -DHAVE_GETTIMEOFDAY -DSNAPSHOT_SUPPORT  -Isrc -Isrc/controllers -Isrc/os_dependent -I/usr/include -I/opt/local/include -I/usr/local/include -Isrc/environment -Isrc/external  -Isrc/games -Isrc/emucore -Isrc/emucore/m6502/src -Isrc/emucore/m6502/src/bspf/src -Isrc/common -Isrc/controllers -Isrc/environment   -c src/external/TinyMT/tinymt32.c -o src/external/TinyMT/tinymt32.o
g++-6    src/main.o src/ale_interface.o src/emucore/AtariVox.o src/emucore/Booster.o src/emucore/Cart2K.o src/emucore/Cart3F.o src/emucore/Cart3E.o src/emucore/Cart4A50.o src/emucore/Cart4K.o src/emucore/CartAR.o src/emucore/CartCV.o src/emucore/Cart.o src/emucore/CartDPC.o src/emucore/CartE0.o src/emucore/CartE7.o src/emucore/CartF4.o src/emucore/CartF4SC.o src/emucore/CartF6.o src/emucore/CartF6SC.o src/emucore/CartF8.o src/emucore/CartF8SC.o src/emucore/CartFASC.o src/emucore/CartFE.o src/emucore/CartMB.o src/emucore/CartMC.o src/emucore/CartUA.o src/emucore/Cart0840.o src/emucore/Console.o src/emucore/Control.o src/emucore/Deserializer.o src/emucore/Driving.o src/emucore/Event.o src/emucore/FSNode.o src/emucore/Joystick.o src/emucore/Keyboard.o src/emucore/M6532.o src/emucore/MD5.o src/emucore/MediaSrc.o src/emucore/OSystem.o src/emucore/Paddles.o src/emucore/Props.o src/emucore/PropsSet.o src/emucore/Random.o src/emucore/Serializer.o src/emucore/Settings.o src/emucore/SpeakJet.o src/emucore/Switches.o src/emucore/TIA.o src/emucore/TIASnd.o src/emucore/m6502/src/Device.o src/emucore/m6502/src/M6502.o src/emucore/m6502/src/M6502Low.o src/emucore/m6502/src/M6502Hi.o src/emucore/m6502/src/NullDev.o src/emucore/m6502/src/System.o src/common/SoundNull.o src/common/SoundSDL.o src/common/SoundExporter.o src/common/display_screen.o src/common/ColourPalette.o src/common/ScreenExporter.o src/common/Constants.o src/common/Log.o src/controllers/ale_controller.o src/controllers/fifo_controller.o src/controllers/rlglue_controller.o src/os_dependent/FSNodePOSIX.o src/os_dependent/OSystemUNIX.o src/os_dependent/SettingsUNIX.o src/games/Roms.o src/games/RomSettings.o src/games/RomUtils.o src/games/supported/Adventure.o src/games/supported/AirRaid.o src/games/supported/Alien.o src/games/supported/Amidar.o src/games/supported/Assault.o src/games/supported/Asterix.o src/games/supported/Asteroids.o src/games/supported/Atlantis.o src/games/supported/BankHeist.o src/games/supported/BattleZone.o src/games/supported/BeamRider.o src/games/supported/Berzerk.o src/games/supported/Bowling.o src/games/supported/Boxing.o src/games/supported/Breakout.o src/games/supported/Carnival.o src/games/supported/Centipede.o src/games/supported/ChopperCommand.o src/games/supported/CrazyClimber.o src/games/supported/Defender.o src/games/supported/DemonAttack.o src/games/supported/DonkeyKong.o src/games/supported/DoubleDunk.o src/games/supported/ElevatorAction.o src/games/supported/Enduro.o src/games/supported/FishingDerby.o src/games/supported/Freeway.o src/games/supported/Frogger.o src/games/supported/Frostbite.o src/games/supported/Galaxian.o src/games/supported/Gopher.o src/games/supported/Gravitar.o src/games/supported/Hero.o src/games/supported/IceHockey.o src/games/supported/JamesBond.o src/games/supported/JourneyEscape.o src/games/supported/Kaboom.o src/games/supported/Kangaroo.o src/games/supported/Koolaid.o src/games/supported/KeystoneKapers.o src/games/supported/Kingkong.o src/games/supported/Krull.o src/games/supported/KungFuMaster.o src/games/supported/LaserGates.o src/games/supported/LostLuggage.o src/games/supported/MontezumaRevenge.o src/games/supported/MrDo.o src/games/supported/MsPacman.o src/games/supported/NameThisGame.o src/games/supported/Phoenix.o src/games/supported/Pitfall.o src/games/supported/Pong.o src/games/supported/Pooyan.o src/games/supported/PrivateEye.o src/games/supported/QBert.o src/games/supported/RiverRaid.o src/games/supported/RoadRunner.o src/games/supported/RoboTank.o src/games/supported/Seaquest.o src/games/supported/SirLancelot.o src/games/supported/Skiing.o src/games/supported/Solaris.o src/games/supported/SpaceInvaders.o src/games/supported/StarGunner.o src/games/supported/Tennis.o src/games/supported/Tetris.o src/games/supported/TimePilot.o src/games/supported/Turmoil.o src/games/supported/Tutankham.o src/games/supported/Trondead.o src/games/supported/UpNDown.o src/games/supported/Venture.o src/games/supported/VideoPinball.o src/games/supported/WizardOfWor.o src/games/supported/YarsRevenge.o src/games/supported/Zaxxon.o src/environment/ale_state.o src/environment/stella_environment.o src/environment/phosphor_blend.o src/external/TinyMT/tinymt32.o   -lz -framework Cocoa -lstdc++  -o ale

**Comment by mgbellemare** [comment]
Hi,

It's possible the makefile isn't up to date anymore -- it's been
half-deprecated for a little while. Did you try cmake?

**Comment by garlicdevs** [comment]
Hi ustcJin,

I have created a friendly patch for a multi-platform purpose. I installed ALE successfully on Mac OS Sierra.
Here is the hard fork of ALE 0.6.0: https://github.com/garlicdevs/Arcade-Learning-Environment
Please read the installation guide and let me know if you cannot install it. 
Have a great day,

**Comment by JesseFarebro** [comment]
We have a new CMake build and no longer support the older Makefiles.
