### ISSUE TITLE
sudo apt-get install libsdl1.2-dev libsdl-gfx1.2-dev libsdl-image1.2-dev not working ?

### ISSUE THREAD

**Issue by chowkamlee81** [mgbellemare/Arcade-Learning-Environment#243]
Above commands are throwing an exception saying that linkage are brpoken.

Iam using ubunty 16.0.4

Kindly rectify the issue so that i can go ahead

**Comment by mgbellemare** [comment]
I'm not sure I understand. Are you saying your APT is unable to install SDL 1.2?
