### ISSUE TITLE
error in 'make -j 4'

### ISSUE THREAD

**Issue by ShangwuYao** [mgbellemare/Arcade-Learning-Environment#244]
Hi, I have trouble in installing it. I am doing this on the AWS Deep Learning AMI (Ubuntu) Version 5.0 - ami-c27af5ba AMI, and in the tensorflow_p36 virtual environment. 

The output after `cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON ..` is:
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /home/ubuntu/anaconda3/envs/tensorflow_p36/bin/cc
-- Check for working C compiler: /home/ubuntu/anaconda3/envs/tensorflow_p36/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/ubuntu/anaconda3/envs/tensorflow_p36/bin/c++
-- Check for working CXX compiler: /home/ubuntu/anaconda3/envs/tensorflow_p36/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find SDL (missing:  SDL_LIBRARY) (found version "1.2.15")
SDL 1.2 not found: You may need to manually edit CMakeLists.txt or run "cmake -i" to specify your SDL path.
CMake Warning (dev) at CMakeLists.txt:225 (FILE):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '
    IF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
      MESSAGE(FATAL_ERROR \"Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")
    ENDIF(NOT EXISTS \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\")

    FILE(READ \"@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt\" files)
    STRING(REGEX REPLACE \"\\n\" \";\" files \"\${files}\")
    FOREACH(file \${files})
      MESSAGE(STATUS \"Uninstalling \"\$ENV{DESTDIR}\${file}\"\")
      IF(EXISTS \"\$ENV{DESTDIR}\${file}\")
        EXEC_PROGRAM(
          \"@CMAKE_COMMAND@\" ARGS \"-E remove \"\$ENV{DESTDIR}\${file}\"\"
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT \"\${rm_retval}\" STREQUAL 0)
          MESSAGE(FATAL_ERROR \"Problem when removing \"\$ENV{DESTDIR}\${file}\"\")
        ENDIF(NOT \"\${rm_retval}\" STREQUAL 0)
      ELSE(EXISTS \"\$ENV{DESTDIR}\${file}\")
        MESSAGE(STATUS \"File \"\$ENV{DESTDIR}\${file}\" does not exist.\")
      ENDIF(EXISTS \"\$ENV{DESTDIR}\${file}\")
    ENDFOREACH(file)
    '

  the old evaluation rules produce:

    '
    IF(NOT EXISTS "/home/ubuntu/Arcade-Learning-Environment/build/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: /home/ubuntu/Arcade-Learning-Environment/build/install_manifest.txt")
    ENDIF(NOT EXISTS "/home/ubuntu/Arcade-Learning-Environment/build/install_manifest.txt")

    FILE(READ "/home/ubuntu/Arcade-Learning-Environment/build/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "/usr/bin/cmake" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  but the new evaluation rules produce:

    '
    IF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
      MESSAGE(FATAL_ERROR "Cannot find install manifest: @CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")
    ENDIF(NOT EXISTS "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt")

    FILE(READ "@CMAKE_CURRENT_BINARY_DIR@/install_manifest.txt" files)
    STRING(REGEX REPLACE "\n" ";" files "${files}")
    FOREACH(file ${files})
      MESSAGE(STATUS "Uninstalling "$ENV{DESTDIR}${file}"")
      IF(EXISTS "$ENV{DESTDIR}${file}")
        EXEC_PROGRAM(
          "@CMAKE_COMMAND@" ARGS "-E remove "$ENV{DESTDIR}${file}""
          OUTPUT_VARIABLE rm_out
          RETURN_VALUE rm_retval
          )
        IF(NOT "${rm_retval}" STREQUAL 0)
          MESSAGE(FATAL_ERROR "Problem when removing "$ENV{DESTDIR}${file}"")
        ENDIF(NOT "${rm_retval}" STREQUAL 0)
      ELSE(EXISTS "$ENV{DESTDIR}${file}")
        MESSAGE(STATUS "File "$ENV{DESTDIR}${file}" does not exist.")
      ENDIF(EXISTS "$ENV{DESTDIR}${file}")
    ENDFOREACH(file)
    '

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Arcade-Learning-Environment/build

**Then after `make -j 4`, I got:** 
Scanning dependencies of target ale-lib
Scanning dependencies of target ale-bin
Scanning dependencies of target ale-c-lib
[  0%] Building CXX object CMakeFiles/ale-lib.dir/src/ale_interface.cpp.o
[  1%] Building CXX object CMakeFiles/ale-c-lib.dir/ale_python_interface/ale_c_wrapper.cpp.o
[  1%] Building CXX object CMakeFiles/ale-bin.dir/src/main.cpp.o
[  2%] Building CXX object CMakeFiles/ale-lib.dir/src/common/display_screen.cpp.o
In file included from /home/ubuntu/Arcade-Learning-Environment/src/emucore/OSystem.hxx:40:0,
                 from /home/ubuntu/Arcade-Learning-Environment/src/ale_interface.hpp:34,
                 from /home/ubuntu/Arcade-Learning-Environment/ale_python_interface/ale_c_wrapper.h:4,
                 from /home/ubuntu/Arcade-Learning-Environment/ale_python_interface/ale_c_wrapper.cpp:1:
/home/ubuntu/Arcade-Learning-Environment/src/emucore/../common/display_screen.h:28:17: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
                 ^
compilation terminated.
In file included from /home/ubuntu/Arcade-Learning-Environment/src/common/display_screen.cpp:16:0:
/home/ubuntu/Arcade-Learning-Environment/src/common/display_screen.h:28:17: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
                 ^
compilation terminated.
CMakeFiles/ale-c-lib.dir/build.make:62: recipe for target 'CMakeFiles/ale-c-lib.dir/ale_python_interface/ale_c_wrapper.cpp.o' failed
make[2]: *** [CMakeFiles/ale-c-lib.dir/ale_python_interface/ale_c_wrapper.cpp.o] Error 1
CMakeFiles/ale-lib.dir/build.make:86: recipe for target 'CMakeFiles/ale-lib.dir/src/common/display_screen.cpp.o' failed
make[2]: *** [CMakeFiles/ale-lib.dir/src/common/display_screen.cpp.o] Error 1
CMakeFiles/Makefile2:210: recipe for target 'CMakeFiles/ale-c-lib.dir/all' failed
make[1]: *** [CMakeFiles/ale-c-lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** Waiting for unfinished jobs....
In file included from /home/ubuntu/Arcade-Learning-Environment/src/emucore/OSystem.hxx:40:0,
                 from /home/ubuntu/Arcade-Learning-Environment/src/ale_interface.hpp:34,
                 from /home/ubuntu/Arcade-Learning-Environment/src/ale_interface.cpp:31:
/home/ubuntu/Arcade-Learning-Environment/src/emucore/../common/display_screen.h:28:17: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
                 ^
compilation terminated.
CMakeFiles/ale-lib.dir/build.make:62: recipe for target 'CMakeFiles/ale-lib.dir/src/ale_interface.cpp.o' failed
make[2]: *** [CMakeFiles/ale-lib.dir/src/ale_interface.cpp.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/ale-lib.dir/all' failed
make[1]: *** [CMakeFiles/ale-lib.dir/all] Error 2
[  2%] Building CXX object CMakeFiles/ale-bin.dir/src/common/display_screen.cpp.o
[  2%] Building CXX object CMakeFiles/ale-bin.dir/src/ale_interface.cpp.o
[  2%] Building CXX object CMakeFiles/ale-bin.dir/src/common/Constants.cpp.o
In file included from /home/ubuntu/Arcade-Learning-Environment/src/emucore/OSystem.hxx:40:0,
                 from /home/ubuntu/Arcade-Learning-Environment/src/main.cpp:23:
/home/ubuntu/Arcade-Learning-Environment/src/emucore/../common/display_screen.h:28:17: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
                 ^
compilation terminated.
CMakeFiles/ale-bin.dir/build.make:62: recipe for target 'CMakeFiles/ale-bin.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/ale-bin.dir/src/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/ubuntu/Arcade-Learning-Environment/src/common/display_screen.cpp:16:0:
/home/ubuntu/Arcade-Learning-Environment/src/common/display_screen.h:28:17: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
                 ^
compilation terminated.
CMakeFiles/ale-bin.dir/build.make:110: recipe for target 'CMakeFiles/ale-bin.dir/src/common/display_screen.cpp.o' failed
make[2]: *** [CMakeFiles/ale-bin.dir/src/common/display_screen.cpp.o] Error 1
In file included from /home/ubuntu/Arcade-Learning-Environment/src/emucore/OSystem.hxx:40:0,
                 from /home/ubuntu/Arcade-Learning-Environment/src/ale_interface.hpp:34,
                 from /home/ubuntu/Arcade-Learning-Environment/src/ale_interface.cpp:31:
/home/ubuntu/Arcade-Learning-Environment/src/emucore/../common/display_screen.h:28:17: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
                 ^
compilation terminated.
CMakeFiles/ale-bin.dir/build.make:86: recipe for target 'CMakeFiles/ale-bin.dir/src/ale_interface.cpp.o' failed
make[2]: *** [CMakeFiles/ale-bin.dir/src/ale_interface.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ale-bin.dir/all' failed
make[1]: *** [CMakeFiles/ale-bin.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

I tried the method from [the other post](https://github.com/mgbellemare/Arcade-Learning-Environment/issues/208), and it didn't work. Thank you.

**Comment by mgbellemare** [comment]
I'm unlikely to be of much help here. Which versions of SDL have you got installed?

**Comment by sidharthramesh98** [comment]
I have version 1.2 installed. Same error occurred. I tried to install it with SDL2 and the error persisted.
Ubuntu 16.04

**Comment by JesseFarebro** [comment]
This shouldn't be an issue with the SDL2 upgrade #368.
