### ISSUE TITLE
Is there a way to know the location of the agent? (i.e. the pixel/euclidean position of the paddle in Pong)?

### ISSUE THREAD

**Issue by aznshodan** [mgbellemare/Arcade-Learning-Environment#249]

**Comment by boluoweifenda** [comment]
I am also interested in it. But I think there is no easy way since the emulator directly reads .bin rom files. Then we need to manually design algorithm for each object in each game.

**Comment by JesseFarebro** [comment]
The recent [Atari Annotated RAM Interface (AtariARI)](https://github.com/mila-iqia/atari-representation-learning) project allows you to query semantic information like sprite locations. Hope this helps!
