### ISSUE TITLE
Failed building wheel for ale-python-interface

### ISSUE THREAD

**Issue by silentobservers** [mgbellemare/Arcade-Learning-Environment#250]
Hi
I am new here and when I try to install python module, I meet a problem like this：
###################################
(tensorflow) jimmy@jimmy-Inspiron-5537:~/git/Arcade-Learning-Environment$ pip install .
Processing /home/jimmy/git/Arcade-Learning-Environment
Building wheels for collected packages: ale-python-interface
  Running setup.py bdist_wheel for ale-python-interface ... error
  Complete output from command /home/jimmy/anaconda3/envs/tensorflow/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-_rwoltbe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-waqy_gst --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/ale_python_interface
  copying ale_python_interface/ale_python_interface.py -> build/lib.linux-x86_64-3.6/ale_python_interface
  copying ale_python_interface/__init__.py -> build/lib.linux-x86_64-3.6/ale_python_interface
  copying ale_python_interface/libale_c.so -> build/lib.linux-x86_64-3.6/ale_python_interface
  running build_ext
  building 'ale_python_interface.ale_c_wrapper' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/ale_python_interface
  gcc -pthread -B /home/jimmy/anaconda3/envs/tensorflow/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/home/jimmy/anaconda3/envs/tensorflow/include/python3.6m -c ale_python_interface/ale_c_wrapper.cpp -o build/temp.linux-x86_64-3.6/ale_python_interface/ale_c_wrapper.o -D__STDC_CONSTANT_MACROS
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  g++ -pthread -shared -B /home/jimmy/anaconda3/envs/tensorflow/compiler_compat -L/home/jimmy/anaconda3/envs/tensorflow/lib -Wl,-rpath=/home/jimmy/anaconda3/envs/tensorflow/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/ale_python_interface/ale_c_wrapper.o -Lale_python_interface -lale_c -o build/lib.linux-x86_64-3.6/ale_python_interface/ale_c_wrapper.cpython-36m-x86_64-linux-gnu.so
  /home/jimmy/anaconda3/envs/tensorflow/compiler_compat/ld: cannot find -lm
  /home/jimmy/anaconda3/envs/tensorflow/compiler_compat/ld: cannot find -lpthread
  /home/jimmy/anaconda3/envs/tensorflow/compiler_compat/ld: cannot find -lc
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ale-python-interface
  Running setup.py clean for ale-python-interface
Failed to build ale-python-interface
Installing collected packages: ale-python-interface
  Running setup.py install for ale-python-interface ... error
    Complete output from command /home/jimmy/anaconda3/envs/tensorflow/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-_rwoltbe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1696v1qv/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ale_python_interface
    copying ale_python_interface/ale_python_interface.py -> build/lib.linux-x86_64-3.6/ale_python_interface
    copying ale_python_interface/__init__.py -> build/lib.linux-x86_64-3.6/ale_python_interface
    copying ale_python_interface/libale_c.so -> build/lib.linux-x86_64-3.6/ale_python_interface
    running build_ext
    building 'ale_python_interface.ale_c_wrapper' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/ale_python_interface
    gcc -pthread -B /home/jimmy/anaconda3/envs/tensorflow/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc -I/home/jimmy/anaconda3/envs/tensorflow/include/python3.6m -c ale_python_interface/ale_c_wrapper.cpp -o build/temp.linux-x86_64-3.6/ale_python_interface/ale_c_wrapper.o -D__STDC_CONSTANT_MACROS
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared -B /home/jimmy/anaconda3/envs/tensorflow/compiler_compat -L/home/jimmy/anaconda3/envs/tensorflow/lib -Wl,-rpath=/home/jimmy/anaconda3/envs/tensorflow/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/ale_python_interface/ale_c_wrapper.o -Lale_python_interface -lale_c -o build/lib.linux-x86_64-3.6/ale_python_interface/ale_c_wrapper.cpython-36m-x86_64-linux-gnu.so
    /home/jimmy/anaconda3/envs/tensorflow/compiler_compat/ld: cannot find -lm
    /home/jimmy/anaconda3/envs/tensorflow/compiler_compat/ld: cannot find -lpthread
    /home/jimmy/anaconda3/envs/tensorflow/compiler_compat/ld: cannot find -lc
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
Command "/home/jimmy/anaconda3/envs/tensorflow/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-_rwoltbe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1696v1qv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-_rwoltbe/

###############################
How to fix this problem and what should I do?
Thanks!

**Comment by super-pirata** [comment]
Hi, I'm new to Git Hub and I don't quite know how this works but I have the same issue... Could anyone help please!

**Comment by JesseFarebro** [comment]
There's a new build system along with a new Python interface using pybind11. This issue is probably outdated now.
