### ISSUE TITLE
How can I setup this Arcade-Learning-Enrironment on Windows system

### ISSUE THREAD

**Issue by canshancai** [mgbellemare/Arcade-Learning-Environment#251]
Dear Mr./Ms,

Many thanks for sharing this great project.
I'd like to use ALE as the environment of RL study on windows, but I noticed the setup is based on Linux/MaC OS right? And tried several effort to setup on windows but failed.

Kindly can I ask you whether you developed latest versions which can work on win os? Or, if I didn't find the right way to setup on win os, kindly can guide me?

PS: My environment is
Win: Win7,64bit
Python: 3.6, 64bit

Many thanks!

**Comment by mgbellemare** [comment]
Hi,

There's a port of ALE for Visual Studio:
https://github.com/Islandman93/Arcade-Learning-Environment

Cheers,
- Marc

**Comment by canshancai** [comment]
Hi, @mgbellemare , Thanks for your reply.

I download your linked repository, and find two sln(in visual project), after compilation with V2015(in src folder), there are many errors tips. It means "https://github.com/Islandman93/Arcade-Learning-Environment" can't compile directly and should modify/replace hxx/cxx muanually, especially we should make useage of "https://github.com/MartinBrazdil/The-Arcade-Learning-Environment-0.4.4-Visual-Studio-2013-Windows-8.1-x64", right? 

Many thanks.

**Comment by mgbellemare** [comment]
Hi,

Unfortunately the Visual Studio port is outside of my area of expertise.
Hopefully someone else can help.

Cheers,
- Marc

**Comment by canshancai** [comment]
Thanks anyway, I think I will setup my Linux environment.

**Comment by cshesse** [comment]
atari_py now has windows wheels available, try `pip install atari_py` https://pypi.org/project/atari-py/#files

**Comment by Pit-Storm** [comment]
All people looking for an answer, see here: https://github.com/openai/gym/issues/1726

**Comment by JesseFarebro** [comment]
The ALE can now be compiled on Windows using dependencies provided by vcpkg.
