### ISSUE TITLE
How to set max_num_frames in python code?

### ISSUE THREAD

**Issue by silentobservers** [mgbellemare/Arcade-Learning-Environment#254]
def __init__(self, rom_file, viz=0,
                 frame_skip=4, nullop_start=30,
                 live_lost_as_eoe=False, max_num_frames=18000):
#############################################################
I have read the manual and found that the argument "max_num_frames" is not available in python.
I try this argument in python code. I set live_lost_as_eoe to be False and no mater how many frames I set, 18000 or 36000, I get nearly same sum rewards. It seems that it does not work in this way.
I wonder if there a convenient method to set the max frames number as an end of one episode in evaluation network performance.

**Comment by mgbellemare** [comment]
You can use setInt("max_num_frames_per_episode", 36000) or something along the like.
