### ISSUE TITLE
Site doesn't work

### ISSUE THREAD

**Issue by cumberb1tch** [mgbellemare/Arcade-Learning-Environment#255]
[Site](http://www.arcadelearningenvironment.org/) doesn't work. 

**It shows:**

```
arcadelearningenvironment.org is almost here!
Upload your website to get started.

Need help? Admin Panel
DreamHost

```

**Comment by JesseFarebro** [comment]
The primary website for the ALE is now this repository. Data from the old site, e.g., Changelog, downloads, documentation can all be found in this repository.
