### ISSUE TITLE
Memory access error (memory dumped)

### ISSUE THREAD

**Issue by Sinerei** [mgbellemare/Arcade-Learning-Environment#257]
Hi
When I try to run, I meet a problem like this：

> A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Game console created:
  ROM file:  /PATH/TO/ROM/DIRECTORY/space_invaders/Space_Invaders.bin
  Cart Name: Space Invaders (1978) (Atari) [!]
  Cart MD5:  72ffbef6504b75e69ee1045af9075f66
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        4096
  Bankswitch Type: AUTO-DETECT ==> 4K
>Screen Display Active. [Manual Control Mode] 'm' [Slowdown] 'a' [Speedup] 's' [VolumeDown] '[' [VolumeUp] ']'.
Running ROM file...
Random seed is 3
Game will be controlled through FIFO pipes.
160-210
>Memory access error (memory dumped)

Also Memory access error !

To run i used this Code:
>./ale -game_controller fifo -random_seed 3 -display_screen true -player_agent single_action_agent -agent_epsilon 0.66 ~/PycharmProjects/DeepRL/ale_0_5/rom/space_invaders/Space_Invaders.bin

So, what am I doing wrong hier?

**Comment by mgbellemare** [comment]
The FIFO controller hasn't been used in a little while, I did test it with the last release but there may be demons in there. Take a look at the example agents in doc/examples -- they're the most up to date.

**Comment by JesseFarebro** [comment]
The FIFO controller is now officially deprecated.
