### ISSUE TITLE
Failed building python module

### ISSUE THREAD

**Issue by PKUfjh** [mgbellemare/Arcade-Learning-Environment#258]
Hi huys, I have a problem in building python module.

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /Users/mengdongbian/Documents/Arcade-Learning-Environment
Building wheels for collected packages: ale-python-interface
  Building wheel for ale-python-interface (setup.py) ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-req-build-2Hui0M/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-wheel-O92wyc --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build/lib.macosx-10.6-intel-2.7
  creating build/lib.macosx-10.6-intel-2.7/ale_python_interface
  copying ale_python_interface/__init__.py -> build/lib.macosx-10.6-intel-2.7/ale_python_interface
  copying ale_python_interface/ale_python_interface.py -> build/lib.macosx-10.6-intel-2.7/ale_python_interface
  copying ale_python_interface/libale_c.so -> build/lib.macosx-10.6-intel-2.7/ale_python_interface
  running build_ext
  building 'ale_python_interface.ale_c_wrapper' extension
  creating build/temp.macosx-10.6-intel-2.7
  creating build/temp.macosx-10.6-intel-2.7/ale_python_interface
  /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Isrc -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ale_python_interface/ale_c_wrapper.cpp -o build/temp.macosx-10.6-intel-2.7/ale_python_interface/ale_c_wrapper.o -D__STDC_CONSTANT_MACROS -std=c++11
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from ale_python_interface/ale_c_wrapper.cpp:1:
  In file included from ale_python_interface/ale_c_wrapper.h:10:
  In file included from src/ale_interface.hpp:33:
  src/emucore/FSNode.hxx:25:10: fatal error: 'algorithm' file not found
  #include <algorithm>
           ^~~~~~~~~~~
  1 warning and 1 error generated.
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ale-python-interface
  Running setup.py clean for ale-python-interface
Failed to build ale-python-interface
Installing collected packages: ale-python-interface
  Running setup.py install for ale-python-interface ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-req-build-2Hui0M/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-record-rDhwRj/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/ale_python_interface
    copying ale_python_interface/__init__.py -> build/lib.macosx-10.6-intel-2.7/ale_python_interface
    copying ale_python_interface/ale_python_interface.py -> build/lib.macosx-10.6-intel-2.7/ale_python_interface
    copying ale_python_interface/libale_c.so -> build/lib.macosx-10.6-intel-2.7/ale_python_interface
    running build_ext
    building 'ale_python_interface.ale_c_wrapper' extension
    creating build/temp.macosx-10.6-intel-2.7
    creating build/temp.macosx-10.6-intel-2.7/ale_python_interface
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Isrc -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ale_python_interface/ale_c_wrapper.cpp -o build/temp.macosx-10.6-intel-2.7/ale_python_interface/ale_c_wrapper.o -D__STDC_CONSTANT_MACROS -std=c++11
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from ale_python_interface/ale_c_wrapper.cpp:1:
    In file included from ale_python_interface/ale_c_wrapper.h:10:
    In file included from src/ale_interface.hpp:33:
    src/emucore/FSNode.hxx:25:10: fatal error: 'algorithm' file not found
    #include <algorithm>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-req-build-2Hui0M/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-record-rDhwRj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_c/_jkd6sds3bl8bz1tp5vh5nvh0000gn/T/pip-req-build-2Hui0M/

**Comment by mgbellemare** [comment]
Hi, I'm not sure what's going on. The python module isn't really maintained, you may want to take a look at atari-py & OpenAI's gym.

**Comment by frederikschubert** [comment]
Apple removed the `/usr/include` directory with XCode 10. There should be a file at `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_*.pkg` that installs them again. 

Also in the `setup.py` the second element in `extra_compile_args` should be `-stdlib=libc++`.

**Comment by JesseFarebro** [comment]
There's a new Python interface using pybind11 along with a new build system, this issue is probably outdated now.
