### ISSUE TITLE
Swift API for ALE

### ISSUE THREAD

**Issue by eaplatanios** [mgbellemare/Arcade-Learning-Environment#266]
@mgbellemare not sure where I should post this, but I thought you might want to know that there is now a [Swift API for ALE](https://github.com/eaplatanios/swift-ale). The code is documented and I will be adding more documentation in the coming days. There is also a working example of learning to play Breakout using PPO and Swift for TensorFlow. :)

**Comment by JesseFarebro** [comment]
Thanks for implementing this! I'm going to close this issue but anyone else looking for Swift bindings can find the link here.
