### ISSUE TITLE
Rendering problems with Python interface

### ISSUE THREAD

**Issue by hernan232** [mgbellemare/Arcade-Learning-Environment#273]
Hi everyone, I was tying to test the ALE environment based on the example in the docs folder with the "asteroids" ROM. I execute the program using SDL and PyGame but sometimes the ship desappears from the screen while the game is executing and the asteroids keeps rendering, and sometimes the ship is rendered but the asteroids are not there. I know that the game is running because the score is changing while the ship desappears. Maybe I am missing some configuration to optimize the rendering. Really I am affraid of saving an image using the library with these errors and then use it in machine learning application.

The source code that I am using is the following:

```
import sys
from random import randrange
from ale_python_interface import ALEInterface
import time

if len(sys.argv) < 2:
    print("Usage: %s rom_file" % sys.argv[0])
    sys.exit()

ale = ALEInterface()

ale.setInt(b"random_seed", 123)

USE_SDL = True
if USE_SDL:
  import pygame
  pygame.init()
  ale.setBool(b"display_screen", True)


# Load the ROM file
rom_file = str.encode(sys.argv[1])
ale.loadROM(rom_file)


# Get the list of legal actions
legal_actions = [0, 1, 2, 3, 4]
print(legal_actions)
# Play 10 episodes
screen = open("screen.txt", "w")
for episode in range(10):
 
  total_reward = 0
 
  if ale.game_over():
      print("It isn't playing")

  while not ale.game_over():
    a = legal_actions[randrange(len(legal_actions))]
    # Apply an action and get the resulting reward
    reward = ale.act(a);
    total_reward += reward

  print('Episode %d ended with score: %d' % (episode, total_reward))
  ale.reset_game()
```

**Comment by hernan232** [comment]
Saving the images of each frame I found that the library renders the asteroids and the ship in an alternate way (i.e. it renders the asteroids first without the ship and then it renders the ship without the asteroids).

At this moment I think I understand the source of this issue. Maybe the rendering does not have enough time to render all the frames and sometimes it skips the ship rendering or the asteroids rendering. But what is the motivation behind this way of render the frames? Why the library does not render the ships and the asteroids in the same frame?

Thank you for help me.

**Comment by mgbellemare** [comment]
Hi,

This is due to the Atari rendering half of the image every other frame, and the renderer dropping even frames. 'colour_averaging' (and max pooling inside more recent algorithms) takes care of this.

Best,
- Marc
