### ISSUE TITLE
No module named 'ale_python_interface'

### ISSUE THREAD

**Issue by soragui** [mgbellemare/Arcade-Learning-Environment#304]
I am on macos 10.15 
follow the readme install step and Successfully installed ale-py-0.6.0.dev0 but when i start the example then with the error :
```bash
  File "python_example_with_modes.py", line 9, in <module>
    from ale_python_interface import ALEInterface
ModuleNotFoundError: No module named 'ale_python_interface'
```

**Comment by JesseFarebro** [comment]
Hi,

We're currently making some changes to the Python interface and the documentation currently doesn't reflect those changes. We have renamed `ale_python_interface` to `ale_py`. So the import would now look like:
```
from ale_py import ALEInterface
```

I hope this helps, the changes to the Python interface should be finalized soon and the documentation updated thereafter.

**Comment by soragui** [comment]
thank you ! problem solved !
