### ISSUE TITLE
Does ALE include the source code of atari games? I means the code using assemble language.

### ISSUE THREAD

**Issue by dxu23nc** [mgbellemare/Arcade-Learning-Environment#306]

**Comment by JesseFarebro** [comment]
No. There are some sources online where you may be able to find annotated assembly code for specific games but the ALE doesn't include this. A lot of the memory addresses we use were found using the Stella debugger from my knowledge.

Hope this helps.

**Comment by dxu23nc** [comment]
Thanks. Could I think that the Real Game is running on Stella, ALE extract some useful info from that to the researchers?

**Comment by JesseFarebro** [comment]
Yes. A supported ROM is run in Stella and we extract the score, # of lives, mode/difficulty, etc. from the emulator's memory.

**Comment by dxu23nc** [comment]
Thanks for your reply.

For the supported ROMs, each ROM should contain the code of how to change the pixels and output them to the 'TV'. And those code is running even if we don't need this process(changing the pixels and output...). Am I correct?  

Thanks in advance.

**Comment by JesseFarebro** [comment]
The games are emulated, this includes emulating the Television Interface Adaptor (TIA) which is responsible for outputting frames. Hopefully, this answers your question.

**Comment by dxu23nc** [comment]
Thanks.
