### ISSUE TITLE
ROM loaded but not running

### ISSUE THREAD

**Issue by Leopounet** [mgbellemare/Arcade-Learning-Environment#307]
Hi,

I recently downloaded and compiled ALE. But when I type this command line:

`./ale -display_screen true -game_controller fifo -random_seed time -sound true freeway.bin`

This gets displayed:

```
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Game console created:
  ROM file:  freeway.bin
  Cart Name: Freeway (1981) (Activision) [!]
  Cart MD5:  8e0ab801b1705a740b476b7f588c6d16
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 0
Game will be controlled through FIFO pipes.
160-210
```

And then nothing else happens. There is also a black screen getting displayed. Can you help me?

**Comment by JesseFarebro** [comment]
You're using the FiFO interface. If this is what you intended to use you should check out the FiFO example: [doc/examples/fifoInterfaceExample.cpp](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/doc/examples/fifoInterfaceExample.cpp) and see the documentation section for the FiFO interface: [doc/manual/manual.pdf](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/doc/manual/manual.pdf).

**Comment by Leopounet** [comment]
This answers my initial question, thank you very much. That being said two other issues showed up, and the answer is not located in the manual this time hopefully.

First, I can't seem to run the example, it returns a segfault.
`Arcade-Learning-Environment$ ./doc/examples/ale-fifoInterfaceExample freeway.bin`
As shown above I start it from the directory in which ale is located. Also, I tried moving the ROM, but it doesn't change anything.

Second, I can't compile with rlglue. I get many lines with similar errors during the `make -j 4` execution.
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/librlutils.so when searching for -lrlutils
``` 
Any idea what causes that to happen? I have rlglue installed, for when I type:
`rl_glue`

This get displayed:
```
RL-Glue Version 3.04, Build 909
RL-Glue is listening for connections on port=4096
```

**Comment by JesseFarebro** [comment]
On a fresh compile I don't receive a segfault when running the FiFO example:
```
$ ./doc/examples/ale-fifoInterfaceExample freeway.bin 
A.L.E: Arcade Learning Environment (version 0.6.0)
[Powered by Stella]
Use -help for help screen.
Game console created:
  ROM file:  freeway.bin
  Cart Name: Freeway (1981) (Activision) [!]
  Cart MD5:  8e0ab801b1705a740b476b7f588c6d16
  Display Format:  AUTO-DETECT ==> NTSC
  ROM Size:        2048
  Bankswitch Type: AUTO-DETECT ==> 2K

Running ROM file...
Random seed is 0
Game will be controlled through FIFO pipes.
ALE says: 160-210

Episode lasted 8192 frames
```
Could you provide more info about your specific setup?

RE RL-Glue: Is there any specific reason you want to use RL-Glue? If you want to use C++ for your agent I would recommend the C++ shared library, see section 3 of the manual and [doc/examples/sharedLibraryInterfaceExample.cpp](https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/doc/examples/sharedLibraryInterfaceExample.cpp).

**Comment by Leopounet** [comment]
I am using Linux Mint 19 Tara on a laptop. 
`uname -a` yields:

```
Linux Leop 4.15.0-48-lowlatency #51-Ubuntu SMP PREEMPT Wed Apr 3 10:17:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I didn't modify the source code of ALE. What other information could help? 

I want to be able to use RL-Glue because I have a school project in which I have to create a similar program as ALE but for Amstrad CPC based on your work. Therefore my version should also allow the user to use it.

**Comment by JesseFarebro** [comment]
Ahh, `popen` doesn't support bidirectional pipes with `r+` on Linux. On macOS it does. On Linux, you could create two file descriptors, one for writing and one for reading.

RE RL-Glue: I'd have to take a look at this later, it hasn't been updated in over a decade so I'll see what I can do.
