### ISSUE TITLE
LibSDL symbol lookup errors

### ISSUE THREAD

**Issue by zenna** [mgbellemare/Arcade-Learning-Environment#31]
I have issues with SDL that I haven't been able to resolve.

When trying to display screen I get

./ale: symbol lookup error: /usr/local/lib/libSDL-1.2.so.0: undefined symbol: _XGetRequest

The problem seems related to:
https://github.com/PerlGameDev/SDL/issues/228

But my installed version of SDL is the latest on ubuntu 14.04 and seems to be after they patched this problem.

Is this an ale problem?

**Comment by mhauskn** [comment]
Hey zenna, are you attempting to display screen on a remote computer via X11? If so it, sounds like it could be an issue with your version of X11 (http://www.linuxquestions.org/questions/slackware-14/libsdl-1-2-so-0-11-4-from-slackware64-current-undefined-symbol-_xgetrequest-4175456708/)

From the error message above it looks like your SDL is installed in a different path than mine. (I believe the default for ubuntu 14.04 is /usr/lib/x86_64-linux-gnu/libSDL.so)

Can you verify that you've installed the following?
sudo apt-get install libsdl1.2-dev
sudo apt-get install libsdl-gfx1.2-dev
sudo apt-get install libsdl-image1.2-dev

Also, I'm assuming you've set the USE_SDL flat inside of makefile.unix to 1 before compiling? Finally can you send the full command you used  to generate the error above (or was it just "./ale")?

**Comment by zenna** [comment]
Thanks, I fixed it

I found I had two versions of SDL, both in where I mentioned and in where you said.  I think it might be because I upgraded from an old version of ubuntu and it seems they are changing their directory structure to support multiarch.

**Comment by mhauskn** [comment]
Glad you were able to fix it! For posterity's sake, can you say what you did to fix the issue?

**Comment by zenna** [comment]
I simply deleted the SDL libraries in /usr/local/lib

**Comment by mhauskn** [comment]
Sounds good. I'm going to go ahead and close the issue.
