### ISSUE TITLE
The paper link in GitHub readme and PyPI description is dead

### ISSUE THREAD

**Issue by justinkterry** [mgbellemare/Arcade-Learning-Environment#317]
The link associated with "The Arcade Learning Environment: An Evaluation Platform for General Agents" returns a 404 error.

**Comment by mgbellemare** [comment]
@JesseFarebro , that link is dead. Could you remove it from the readme/pypi? Thanks!

**Comment by JesseFarebro** [comment]
Updated the paper link and the build badge. I wanted to do a larger overhaul of the documentation and README once #328 is dealt with.
