### ISSUE TITLE
ALE-Py Packaging issue

### ISSUE THREAD

**Issue by justinkterry** [mgbellemare/Arcade-Learning-Environment#334]
@JesseFarebro Hopefully I'm not missing something stupid, but when I to install from PyPI on Debian 9.12 and Python 3.5, it won't install and it's not obvious to me why:

```
justinkterry@instance-1:~$ pip3 install ale-py==0.6.0.dev20200207
Collecting ale-py==0.6.0.dev20200207
  Could not find a version that satisfies the requirement ale-py==0.6.0.dev20200207 (from versions: )
No matching distribution found for ale-py==0.6.0.dev20200207
justinkterry@instance-1:~$ pip install ale-py==0.6.0.dev20200207
-bash: pip: command not found
justinkterry@instance-1:~$ sudo pip3 install ale-py
Collecting ale-py
  Could not find a version that satisfies the requirement ale-py (from versions: )
No matching distribution found for ale-py
justinkterry@instance-1:~$ sudo pip3 install ale_py
Collecting ale_py
  Could not find a version that satisfies the requirement ale_py (from versions: )
No matching distribution found for ale_py
justinkterry@instance-1:~$ pip install ale_py==0.6.0.dev20200207
-bash: pip: command not found
justinkterry@instance-1:~$ pip3 install ale_py==0.6.0.dev20200207
Collecting ale_py==0.6.0.dev20200207
  Could not find a version that satisfies the requirement ale_py==0.6.0.dev20200207 (from versions: )
No matching distribution found for ale_py==0.6.0.dev20200207
ustinkterry@instance-1:~$ pip3 install ale-py 0.6.0.dev20200207
Collecting ale-py
  Could not find a version that satisfies the requirement ale-py (from versions: )
No matching distribution found for ale-py
```

**Comment by justinkterry** [comment]
pip3 install ale-py works on macOS catalina with Python 3.7

**Comment by JesseFarebro** [comment]
Make sure pip is up to date. Also, can you post the output of:

```python
import wheel.pep425tags
print(wheel.pep425tags.get_supported())
```

**Comment by justinkterry** [comment]
I'm using the version of pip that comes from the apt repo on the current version of Debian, upgrading pip beyond what's in apt is a nightmare. Here's the command you asked for:

>>> import wheel.pep425tags
>>> print(wheel.pep425tags.get_supported())
[('cp35', 'cp35m', 'linux_x86_64'), ('cp35', 'abi3', 'linux_x86_64'), ('cp35', 'none', 'linux_x86_64'), ('cp35', 'none', 'any
'), ('cp3', 'none', 'any'), ('cp34', 'none', 'any'), ('cp33', 'none', 'any'), ('cp32', 'none', 'any'), ('cp31', 'none', 'any'
), ('cp30', 'none', 'any'), ('py3', 'none', 'linux_x86_64'), ('py35', 'none', 'any'), ('py3', 'none', 'any'), ('py34', 'none'
, 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), ('py30', 'none', 'any')]

**Comment by JesseFarebro** [comment]
So it seems your current setup doesn't support any `manylinux` compatible wheels. We use the `manylinux2010` standard for packaging our wheels. `manylinux` standardizes builds on Linux so there is some guarantees for glibc, ABI compatibility, etc. Many packages do this, for example, try installing `tensorflow==2.1.0`, it won't work either.

This isn't to say it can't run on your system, it's just that pip determined your system isn't compatible. I believe a workaround is to add a file named `_manylinux.py` in your path with the following:
```python
manylinux1_compatible = True
manylinux2010_compatible = True
```

Just make sure that if you `import sys; print(sys.path)` that the file `_manylinux.py` shows up with those two lines. Hopefully, that works for you, if not you might be able to build the Python package yourself on this machine.

**Comment by JesseFarebro** [comment]
@justinkterry you should really just create a virtualenv where you can upgrade pip and then try again.

**Comment by justinkterry** [comment]
Fair enough, thanks a ton
