### ISSUE TITLE
Missing checksums for new game ROMs

### ISSUE THREAD

**Issue by justinkterry** [mgbellemare/Arcade-Learning-Environment#336]
@tkoeppe The 30 new games you added didn't get MD5s for them added to the list: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/md5.txt

This is needed to verify you're using the right ROM for the code. Can you please look into this?

**Comment by justinkterry** [comment]
It turns out all the relevant md5s checksums are already in here, but elsewhere?:

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/emucore/stella.pro

**Comment by tkoeppe** [comment]
I'll see that we collect those checksums; but the verification is not fatal, right?

**Comment by justinkterry** [comment]
It's not fatal. Someone who works with me also submitted a PR for this- #338
