### ISSUE TITLE
Md5 warning emitted all the time in ale_py

### ISSUE THREAD

**Issue by weepingwillowben** [mgbellemare/Arcade-Learning-Environment#337]
So when the ale_interface is used to load a ROM, it checks for a `md5.txt` file in the current working directory here:
https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/ale_interface.cpp#L76

before emitting a warning here:

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/ale_interface.cpp#L112

This is not optimal, as it spits out warning whenever that md5.txt isn't around, which is typically 100% of the time if you are using ale_py. 
@JesseFarebro

**Comment by justinkterry** [comment]
To fix this, the md5.txt would have to be included with the PyPI release, and the code would have to be refactored to check in that directory. Having the check be for the current working directory seems odd to me.

**Comment by JesseFarebro** [comment]
Yeah, I agree. It's been like this for a long time, I think a better solution is to actually do md5 validation when loading the ROM. Right now we just check against a filename, e.g. `Freeway.bin` won't load but `freeway.bin` will.

@mgbellemare was there a reason you didn't want to enforce md5 validation?

**Comment by tkoeppe** [comment]
(Same agreement here; the overly simplistic file handling logic made it impractical for us to try and meaningfully distribute and use the checksums. We just ignore the warning. A proper solution would perhaps a) make the path configurable via flag or setting, or b) hardcode the numbers in the program code.)

**Comment by justinkterry** [comment]
Is the plan to handle this logic here, or in Gym?

**Comment by JesseFarebro** [comment]
In the ALE I'm thinking, once #328 is dealt with I will make sure the md5 list is packaged properly so we don't have these extraneous warnings.

**Comment by JesseFarebro** [comment]
All warnings regarding MD5 mismatches can now be taken seriously with #356. There are no breaking changes, and loading ROMs is now more robust. Both the old snake case naming convention as well as MD5 matching will be valid from now on.
