### ISSUE TITLE
New backgammon env crashes and we can't figure out why

### ISSUE THREAD

**Issue by justinkterry** [mgbellemare/Arcade-Learning-Environment#339]
@tkoeppe 

All the new games you added work great, except that when we load backgammon it freezes for some strange reason and fails to ever load. Me, @MarioJayakumar, and @weepingwillowben all looked at it and it's not for an immediately obvious reason either. We're also using the backgammon ROM stella supports, from https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/emucore/stella.pro

Code to reproduce:

```
import ale_py
install_dir = ale_py.__file__
install_dir = install_dir[:-11] + "ROM/"
ale = ale_py.ALEInterface()
g =  install_dir+"backgammon/backgammon.bin"
ale.loadROM(g)
```

**Comment by JesseFarebro** [comment]
There was a discussion in #327 and it's fixed by #335. The change is minimal, I'll go ahead and merge it now.
