### ISSUE TITLE
How can I convert the RGB images to their 4 bit representation?

### ISSUE THREAD

**Issue by danijar** [mgbellemare/Arcade-Learning-Environment#340]
My understanding is that there are only 16 colors on the Atari 2600 console. I'm using the Python bindings through Gym, which return images as `np.uint8` with 1 (grayscale) or 3 (RGB) channels. Where can I find the mapping to convert these back to the original 4 bit representation to store frames with lower memory footprint?

**Comment by mgbellemare** [comment]
Hi Danijar,

128, actually (from the NTSC palette). The ALE actually returns these integers directly, so if you disable the mapping to RGB in your interface you should be able get them.

**Comment by danijar** [comment]
I see, thanks! Since it's 128 colors, I'll find another way of compressing it to save memory.
