### ISSUE TITLE
You accidentally put roadrunner in md5.txt twice

### ISSUE THREAD

**Issue by justinkterry** [mgbellemare/Arcade-Learning-Environment#345]
@tkoeppe in PR #343 you accidentally added two different MD5s for roadrunner:

```
2bd00beefdb424fa39931a75e890695d road_runner.bin
ce5cc62608be2cd3ed8abd844efb8919 road_runner.bin
```

**Comment by JesseFarebro** [comment]
Only recently Gym patched the NTSC version (`ce5cc62608be2cd3ed8abd844efb8919`) to match the PAL version (`2bd00beefdb424fa39931a75e890695d`). I don't even think the PAL version has been deployed in Gym as they still use an older version of atari-py.

It's probably safe to go with the NTSC version `ce5cc62608be2cd3ed8abd844efb8919`, the one @tkoeppe added. It seems difficult to find the PAL version.

**Comment by justinkterry** [comment]
Do you want me to submit a small PR to remove the PAL version then?

**Comment by hholst80** [comment]
Certainly they should not have the same filename. Do not reinvent the wheel. Follow the TOSEC naming schema if you are going down this path with multiple versions of the same game.

https://www.tosecdev.org/tosec-naming-convention

**Comment by JesseFarebro** [comment]
@hholst80 the MD5 list doesn't support multiple versions of the same game, this was simply a mistake. The MD5 list is so we can at least attempt to have a single source of truth for supported ROMs in the ALE so researchers can compare results.

@justinkterry I'm not even sure anymore, upon further investigation Gym uses a different version entirely:
```
MD5 (road_runner.bin) = 7d3cdde63b16fa637c4484e716839c94
```

The ROM info is:
```
"Cart.MD5" "7d3cdde63b16fa637c4484e716839c94"
"Cart.Manufacturer" "CCE"
"Cart.Name" "Road Runner (CCE)"
```

From what I can tell CCE produced games in Brazil mainly. I still think going with the official Atari NTSC version `ce5cc62608be2cd3ed8abd844efb8919` is probably the right way to go.

**Comment by tkoeppe** [comment]
Sorry about this. I've asked for our situation to be clarified, but as always, we have no deep interest in this checking mechanism, and if there's a particular thing you prefer, feel free to do that.

**Comment by justinkterry** [comment]
@JesseFarebro Gym using the brazilian version seems like a problem on Gym's end..?

**Comment by JesseFarebro** [comment]
I mean the concern with all of this is comparing results. I’m guessing most published results use Gym so we have to be careful w.r.t what ROMs they are using.
I’m not sure why they made that choice. I still think going with the Atari official NTSC version is the best course of action.

**Comment by justinkterry** [comment]
I agree that going with the NTSC version is the best course of action, it's just that when Gym moves to ALE-Py it seems like that will cause issues. In theory, Gym switch to the NTSC version and up the version number though?

**Comment by kieranhj** [comment]
Curiously the original ROM referenced in the md5.txt list:

`2bd00beefdb424fa39931a75e890695d road_runner.bin`

is no longer recognised in the latest version of Stella as a valid Road Runner ROM variant. However, upon testing it is an NTSC ROM, not PAL.

Given that obtaining a ROM binary with this md5 might now be difficult, if it's not in any official collections, it probably makes sense to standardise on the official NTSC version `ce5cc62608be2cd3ed8abd844efb8919` as proposed.

**Comment by JesseFarebro** [comment]
@justinkterry the plan was to bump the version number of all ALE games in Gym with the release of ale-py.
