### ISSUE TITLE
wizard of wor not working

### ISSUE THREAD

**Issue by weepingwillowben** [mgbellemare/Arcade-Learning-Environment#346]
I am trying to run the games and make sure they are controllable, and Wizard of Wor is not for some reason. 

I am choosing random actions and the behavior I actually see is as if I am continually choosing the no-op action. The player eventually gets kicked out of the waiting area and eventually gets killed by the NPCs without ever firing a single bullet or moving anywhere. 

Is there some trick to getting this game working? I have gotten over a dozen other games working just fine. 

Here is the code I am running:

```python
import ale_py
from random import randrange
import pygame
import numpy as np
import time

pygame.init()

ale = ale_py.ALEInterface()

BOX_PIX = 3
BSX = 160
BSY = 210
screen = pygame.display.set_mode((BSX*BOX_PIX, BSY*BOX_PIX))

ale.loadROM("wizard_of_wor.bin")

legal_actions = ale.getMinimalActionSet()

for episode in range(10):
  total_reward = 0
  while not ale.game_over():
    a = legal_actions[randrange(len(legal_actions))]

    for _ in range(5):
        reward = ale.act(a)
        total_reward += reward
    time.sleep(0.02)
    image = ale.getScreenRGB()
    image = np.transpose(image,(1,0,2))
    #print(image.shape)

    myImage = pygame.image.fromstring(image.tobytes(), image.shape[:2][::-1], "RGB")

    #surf = pygame.surfarray.make_surface(image)
    screen.fill((0,0,0))
    screen.blit(myImage, (0, 0))

    pygame.display.flip()

  ale.reset_game()
print(total_reward)
```

**Comment by JesseFarebro** [comment]
I've noticed this myself as well. I believe this issue is not just related to Wizard of Wor. I will take a deeper look at this soon and get back to you.

**Comment by JesseFarebro** [comment]
PR #347 solves this issue. There hasn't been a release since this issue was introduced so the impact is minimal.

**Comment by weepingwillowben** [comment]
Thanks for looking into this. Indeed, this seems to fix the issue.

**Comment by weepingwillowben** [comment]
Closing because this issue has been fixed.
