### ISSUE TITLE
Verified MD5 hashes of several games

### ISSUE THREAD

**Issue by MarioJayakumar** [mgbellemare/Arcade-Learning-Environment#349]
For Asteroid, Blackjack, Lost Luggage, Private Eye, and Space War, I am currently unable to find ROMs that have the same MD5 hash as those specified in md5.txt. I have tried several different ROMs on various sites, using both NTSC and PAL, and yet none of the ROMs have a correct hash. I also saw in issue #345  that these ROMs may potentially be using a completely different version like Road Runner was. Could you verify that the MD5 hash that is listed is indeed correct and if so what format, language, or version that correct ROM is using? I am working on this with Justin Terry and Ben Black.

**Comment by justinkterry** [comment]
@JesseFarebro

**Comment by JesseFarebro** [comment]
Regarding Asteroids and Private Eye, OpenAI uses the same hash as we do so I'd be hesitant to change this. Regardless, all of these ROMs can be found, for example, you can check out the ROM download instructions on https://github.com/openai/atari-py.

Hope this helps.

**Comment by justinkterry** [comment]
As far as we can tell, ROMs matching ALE's MD5s are only available in that rar file. We can't find them anywhere else, even on atarimania. Surely this is undesirable?

**Comment by MarioJayakumar** [comment]
To add on to this, I compared the MD5 checksum of the ROMs included in the RAR file and all of  hashes match what we want. For example the correct version of Asteroids is available in this RAR file, as a ROM from Sears. However on Atarimania's page for Asteroids, the Asteroids ROM with this same serial and also from Sears does not have a matching MD5 hash. This indicates that either the link on Atarimania is broken or that the version distributed in the RAR is not available elsewhere on the site.

**Comment by JesseFarebro** [comment]
Are these 5 ROMs the only you can't find through other sources?

I'd have to take a deeper look, could you do a diff to get a sense of how much they differ?

**Comment by MarioJayakumar** [comment]
Yes these 5 ROMs are the only ones I could not find on any other website, apart from this RAR. Are you saying that I should do a diff of each version of each ROM?

**Comment by JesseFarebro** [comment]
What I meant is maybe start by doing a diff of the two Asteroids ROMs from Sears and see how much they differ. I'm curious about what changes between two seemingly equivalent ROMs by the same distributor. I wonder where Stella has compiled the `stella.pro` file from, perhaps there is more information to be had.

**Comment by MarioJayakumar** [comment]
Hmm so I performed a diff of the two Sears binaries. I found that there are 129 differences between the two binary files. I'm not sure how I can share it with you. Additionally, the changes seem to be sporadic at the end of the file, despite both ROMs being Sears. The only difference in the file name is that the one we want has [no copyright] in the title.

**Comment by MarioJayakumar** [comment]
Hey @JesseFarebro I just wanted to follow up on this and see if there is any update on whether there is an actual difference between the two Asteroid ROMs and other roms

**Comment by JesseFarebro** [comment]
All the current MD5 hashes are the ones we primarily support. The old set of games (i.e., before #327) should be widely available.
