### ISSUE TITLE
README references invalid documentation link

### ISSUE THREAD

**Issue by nkconnor** [mgbellemare/Arcade-Learning-Environment#351]
See arcadelearningenvironment.org

**Comment by nkconnor** [comment]
there's at least a couple more dead links. another one: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/doc/manual/manual.pdf

**Comment by JesseFarebro** [comment]
The primary website for the ALE is now this repository. Data from the old site, e.g., Changelog, downloads, documentation can all be found in this repository.

The other dead links have been taken care of. Thanks!
