### ISSUE TITLE
RuntimeError: Unable to find ALEVERSION in CMakeLists.txt

### ISSUE THREAD

**Issue by THSWind** [mgbellemare/Arcade-Learning-Environment#360]
To install the Python module:
$ pip install .

After I run it in ./Arcade-Learning-Environment$, some error occurs, as following, Help me plllz

    ERROR: Command errored out with exit status 1:
     command: /home/sdb/team_AI/zoulong/anaconda3/envs/py2.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-GIQSJY/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-GIQSJY/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-GIQSJY/pip-egg-info
         cwd: /tmp/pip-req-build-GIQSJY/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-GIQSJY/setup.py", line 136, in <module>
        version=_parse_version("CMakeLists.txt"),
      File "/tmp/pip-req-build-GIQSJY/setup.py", line 110, in _parse_version
        raise RuntimeError("Unable to find ALEVERSION in %s" % filename)
    RuntimeError: Unable to find ALEVERSION in CMakeLists.txt
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by JesseFarebro** [comment]
Hi,

Right now you can install a dev build from here: [https://pypi.org/project/ale-py](https://pypi.org/project/ale-py/), i.e., `pip install ale-py`, or you can build from the Pybind11 branch (`git clone https://github.com/JesseFarebro/Arcade-Learning-Environment -b pybind11`) which fixes these issues. We've been reworking how the Python interface works (#354), sorry for the inconvenience.

**Comment by THSWind** [comment]
> Hi,
> 
> Right now you can install a dev build from here: [https://pypi.org/project/ale-py](https://pypi.org/project/ale-py/), i.e., `pip install ale-py`, or you can build from the Pybind11 branch (`git clone https://github.com/JesseFarebro/Arcade-Learning-Environment -b pybind11`) which fixes these issues. We've been reworking how the Python interface works (#354), sorry for the inconvenience.

Thanks for your replay, 
But it doesn't work too, a new error occurs:


    ERROR: Command errored out with exit status 1:
     command: /home/sdb/team_AI/zoulong/anaconda3/envs/py2.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-kZFck_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-kZFck_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-kZFck_/pip-egg-info
         cwd: /tmp/pip-req-build-kZFck_/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-kZFck_/setup.py", line 197, in <module>
        test_requires=["pytest"],
      File "/home/sdb/team_AI/zoulong/anaconda3/envs/py2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/home/sdb/team_AI/zoulong/anaconda3/envs/py2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-req-build-kZFck_/setup.py", line 29, in __init__
        super().__init__(attrs)
    TypeError: super() takes at least 1 argument (0 given)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by JesseFarebro** [comment]
Try using a Python 3 based environment. Python 2 was sunset January 1st this year and the new Python wrapper only supports 3.5+.

**Comment by THSWind** [comment]
> Try using a Python 3 based environment. Python 2 was sunset January 1st this year and the new Python wrapper only supports 3.5+.

okay, thanks for your help~, I will try it

**Comment by THSWind** [comment]
> Try using a Python 3 based environment. Python 2 was sunset January 1st this year and the new Python wrapper only supports 3.5+.

Can you tell me if there is something like a document for installing ALE in python2.7? My code ability is not good. There are many problems in rewriting the code of python2 to python3, which can not be solved........

**Comment by JesseFarebro** [comment]
Just use the latest release, i.e., `git clone https://github.com/mgbellemare/Arcade-Learning-Environment -b v0.6.1`, v0.6.1 uses the old Python interface which supports 2.7.

**Comment by THSWind** [comment]
> Just use the latest release, i.e., `git clone https://github.com/mgbellemare/Arcade-Learning-Environment -b v0.6.1`, v0.6.1 uses the old Python interface which supports 2.7.

Wow! it works, thank you very very very much, YOU ARE TOO KIND
