### ISSUE TITLE
Do you train the linear approximation parameters θ for every game in test set?

### ISSUE THREAD

**Issue by wozxfdha** [mgbellemare/Arcade-Learning-Environment#371]
sorry I'm new to rl, hope someone can help me.

you just use the train set to find super parameters, not include a θ used for all games. 

For a game in test set, you fix the super parameters and train θ to approximate value function. After it done, agent interacts with game, and get the final score.

Right?

**Comment by JesseFarebro** [comment]
This depends on what problem setting you're looking at. In general, you won't train on one environment and test on another. You'd train on one environment (i.e., a game in this case) and evaluate your performance in that same environment.

If you're new to RL you can follow along with these courses to get a better idea of the RL problem: [https://www.coursera.org/specializations/reinforcement-learning](https://www.coursera.org/specializations/reinforcement-learning).
