### ISSUE TITLE
Error in "pip install . " and "pip install --user ."

### ISSUE THREAD

**Issue by danielmateos99** [mgbellemare/Arcade-Learning-Environment#376]
Hi, i tried to solve it but I keep having the same problem. If someone knows why I have this error and knows how to solve it, I would appreciate it

pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/dedalo/Escritorio/ALE
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from ale-py==0.6.1.dev0) (1.17.4)
Building wheels for collected packages: ale-py
  Building wheel for ale-py (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpudn9r9ml
       cwd: /tmp/pip-req-build-488vcvuh
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_ext
  creating build/temp.linux-x86_64-3.8
  creating /tmp/pip-req-build-488vcvuh/build/lib.linux-x86_64-3.8
  cmake /tmp/pip-req-build-488vcvuh -DCMAKE_BUILD_TYPE=Release -DUSE_SDL=OFF -DBUILD_CPP_LIB=OFF -DBUILD_PYTHON=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-488vcvuh/build/lib.linux-x86_64-3.8 -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-488vcvuh/build/lib.linux-x86_64-3.8 -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-488vcvuh/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/usr/bin/python3
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-488vcvuh/CMakeCache.txt is different than the directory /home/dedalo/Escritorio/ALE where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
    warnings.warn(msg)
  error: command 'cmake' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ale-py
Failed to build ale-py
ERROR: Could not build wheels for ale-py which use PEP 517 and cannot be installed directly

**Comment by JesseFarebro** [comment]
Can you try manually building the wheel instead of using `pip install .`, i.e., try running `python setup.py bdist_wheel`.

**Comment by danielmateos99** [comment]
I get this 

python setup.py bdist_wheel .
Traceback (most recent call last):
  File "setup.py", line 195, in <module>
    test_requires=["pytest"],
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "setup.py", line 29, in __init__
    super().__init__(attrs)
TypeError: super() takes at least 1 argument (0 given)

**Comment by JesseFarebro** [comment]
You ran it with Python 2. We don't support 2.X. Try with Python 3.6+ and let me know how it goes.
