### ISSUE TITLE
Error in command line cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON ..

### ISSUE THREAD

**Issue by danielmateos99** [mgbellemare/Arcade-Learning-Environment#378]
I have pyhton3.8.5 installed and I get this error:

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Python3 (missing: Python3_INCLUDE_DIRS Interpreter
  Development) (found version "3.8")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
  /usr/share/cmake-3.16/Modules/FindPython3.cmake:300 (include)
  src/CMakeLists.txt:72 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dani/ALE/build/CMakeFiles/CMakeOutput.log".
See also "/home/dani/ALE/build/CMakeFiles/CMakeError.log".

 I have thought that it may be a path error and I have tried to change it, but it does not work
Thanks for your attention

**Comment by JesseFarebro** [comment]
Some more info on your setup would be helpful. Depending on your distro there's usually a Python development package, e.g., on Ubuntu you'd have to install `python3-dev`. Another alternative which I'd recommend is using something like [pyenv](https://github.com/pyenv/pyenv) to manage your Python installs.

**Comment by danielmateos99** [comment]
Yes, I installed the python developer package and it worked!

**Comment by JesseFarebro** [comment]
No problem!
