### ISSUE TITLE
Can't use ./ale -help

### ISSUE THREAD

**Issue by danielmateos99** [mgbellemare/Arcade-Learning-Environment#393]
I can't use `./ale -help` it says that the directory does not exist, and if i try to open a ROM like `./ale -game_conroller fifo -display_screen true tetris.bin`, i get the same.

Unfortunately, the documentation isn't available and I don't know what I'm doing wrong.

**Comment by JesseFarebro** [comment]
The CLI has been deprecated and the documentation doesn't currently reflect this. I plan to have some updated docs in the next couple of days. For now, I'd recommend using the latest tag `v0.6.1` which does reflect the current documentation.
