### ISSUE TITLE
Error finding videoRecordingExample

### ISSUE THREAD

**Issue by danielmateos99** [mgbellemare/Arcade-Learning-Environment#403]
When running `doc/examples/videoRecordingExample freeway.bin` in terminal
I get that "bash: doc/examples/videoRecordingExample: No such file or directory" but it is there. I have the game in the ALE folder and videoRecordingExample.cpp in the corresponding path.

**Comment by JesseFarebro** [comment]
I'm assuming you're using the `v0.6.1` tag and the examples folder is still located inside `doc/`. You've also made sure you compiled the program `videoRecordingExample`?

**Comment by danielmateos99** [comment]
Yes, I'm using the `v0.6.1` and the path is correct. I compiled it using `make doc/examples/videoRecordingExample` and I get this:

`g++     doc/examples/videoRecordingExample.cpp   -o doc/examples/videoRecordingExample
doc/examples/videoRecordingExample.cpp:19:10: fatal error: ale_interface.hpp:  No such file or directory
   19 | #include <ale_interface.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<integrado>: doc/examples/videoRecordingExample] Error 1
`

**Comment by JesseFarebro** [comment]
You should probably build the examples in the `doc/examples` directory, the Makefile uses relative paths and may not work from the root directory. Your make command also isn't valid, you should run `make -f Makefile.recording`.

**Comment by danielmateos99** [comment]
Thanks, I tried it and now when I put `doc/examples/videoRecordingExample freeway.bin` in the ALE folder i get `doc/examples/videoRecordingExample: error while loading shared libraries: libale.so: cannot open shared object file: No such file or directory` and if I do it in the `doc/examples` directory using `videoRecordingExample freeway.bin` i get `videoRecordingExample: order not found`.

**Comment by JesseFarebro** [comment]
If you don't have the ALE installed, i.e., `make install` the library, you should just build the examples from the main CMake file. You should be able to run this successfully

```sh
git clone https://github.com/mgbellemare/Arcade-Learning-Environment && cd Arcade-Learning-Environment
git checkout tags/v0.6.1
mkdir build && cd build
cmake ../ -DUSE_SDL=ON -DBUILD_EXAMPLES=ON && make && cd ../
./doc/examples/ale-videoRecordingExample freeway.bin
```

**Comment by danielmateos99** [comment]
I works! Thanks again Jesse!
