### ISSUE TITLE
Error installing sdl lib from vcpkg

### ISSUE THREAD

**Issue by Adrii98** [mgbellemare/Arcade-Learning-Environment#404]
When running `./vcpkg/vcpkg install zlib sdl` in the terminal, the result of the command is `Error: while loading port sdl: Port definition not found`. What can i do to solve this problem?

**Comment by JesseFarebro** [comment]
Sorry, that seems to be a typo, the package name should be `sdl1`. Can you try:

```sh
vcpkg install zlib sdl1
```
