### ISSUE TITLE
User moves

### ISSUE THREAD

**Issue by Adrii98** [mgbellemare/Arcade-Learning-Environment#407]
Hi, i am trying to obtain the moves that the user or the AI are doing while playing a game. Is there any form or script to do that in an easy way?
Thanks in advance

**Comment by JesseFarebro** [comment]
I'm not quite sure I follow. If an agent is submitting actions to the environment you should be able to record these easily. On the other hand, if you want a human to play and record those actions you'd have to write a script to do so yourself. OpenAI Gym simplifies this process a little, check out their solution here https://github.com/openai/gym/blob/master/gym/utils/play.py.
