### ISSUE TITLE
Feature Construction

### ISSUE THREAD

**Issue by 1412540568** [mgbellemare/Arcade-Learning-Environment#409]
Can you publicly provide the algorithm SARSA feature extraction source code?
I hope to improve the corresponding theory on this basis.
thank you!
[1]The Arcade Learning Environment: An Evaluation Platform for General Agents.

**Comment by JesseFarebro** [comment]
I'm not sure that the original feature extractors are available, but some of them (e.g., Basic, BASS, RAM) are implemented in the following repository by Marlos Machado: [https://github.com/mcmachado/ALEResearch/tree/master/src/features](https://github.com/mcmachado/ALEResearch/tree/master/src/features). You can also find the BLOB-* features used in followup works (e.g., [1], [2]) here: [https://github.com/mcmachado/b-pro](https://github.com/mcmachado/b-pro). Hope that helps.

[1] [State of the Art Control of Atari Games
Using Shallow Reinforcement Learning](https://arxiv.org/abs/1512.01563)
[2] [Revisiting the Arcade Learning Environment: Evaluation Protocols and Open Problems for General Agents](https://arxiv.org/abs/1709.06009)

**Comment by 1412540568** [comment]
Thanks a lot. And do you konw why the website "arcadelearningenvironment.org" is down?

**Comment by JesseFarebro** [comment]
No problem! Yes, the website has been down for a while but we have plans for a really cool website coming soon.
