### ISSUE TITLE
Surround Fail to run in gym 

### ISSUE THREAD

**Issue by fjj2544** [mgbellemare/Arcade-Learning-Environment#410]

**Comment by JesseFarebro** [comment]
Hi,

I see you edited your issue, did you end up resolving your issue? From your original post, I believe you were installing an outdated version of the ALE that didn't support Surround. It should work if you run,

```sh
git clone https://github.com/mgbellemare/Arcade-Learning-Environment
cd Arcade-Learning-Environment
pip install .
```
with the accompanying dependencies installed as you had done in your original post.
