### ISSUE TITLE
SDL error 

### ISSUE THREAD

**Issue by Adrii98** [mgbellemare/Arcade-Learning-Environment#411]
Hi, i am trying to run the ALE from an script made by me but an error with SDL appears.  When `USE_SDL `is defined i get the error that SDL is not defined and i get the suggestion of recompilation with `-DUSE_SDL=ON` but i already have done it. I think that this error is due to the fact that my file is not considered in the process of cmake compilation. There's any way the cmake process can take into account my cpp file.
Thanks in advance

**Comment by JesseFarebro** [comment]
Could you provide me with some extra details on how you're compiling the ALE? Also, could you provide the actual terminal output when the error is thrown? I'm not exactly sure what error you're running into right now. Thanks!

**Comment by Adrii98** [comment]
What  i want to know is how can ir run the ale from an external file. Do i have to change something in the makefile?

**Comment by JesseFarebro** [comment]
It sounds like you're using C++, so I take it you've built and installed the ALE with something like,

```sh
git clone https://github.com/mgbellemare/Arcade-Learning-Environment && cd Arcade-Learning-Environment
mkdir build; cd build
cmake ../
make -j12 && make install
```

Then in your C++ project you have to link to the ALE, e.g., in your `CMakeLists.txt`:

```cmake
find_package(ale REQUIRED)

add_executable(my_target my_file.cpp)
target_link_libraries(my_target ale::ale-lib)
```

**Comment by Adrii98** [comment]
Do i have to put those lines inside de if(unix) part or just at the final of the file?

**Comment by JesseFarebro** [comment]
You shouldn't be modifying the `CMakeLists.txt` file in the ALE. Make a different directory for your project with its own `CMakeLists.txt`.

**Comment by Adrii98** [comment]
I have another doubt, where i have to put the new CMakeLists.txt also with my .cpp file? Can i just put it in another folder outside the ALE or both files have be inside the ALE folder.
Also in my cpp i am trying to call some matlab functions i made so its necessary to use some Matlab libraries for the compilation of the program. Do i have to put those libraries in the CmakeList.txt?
Thanks in advance

**Comment by JesseFarebro** [comment]
Yes, your project should be outside of the main ALE folder. You should build and install the ALE and then you could even delete the ALE folder if you'd like. I'm not familiar with how Matlab interfaces with C++ so I can't really help you there. I'm sure there are resources online for doing this using CMake.
