### ISSUE TITLE
How to add include paths in the cmake for the videorecordingexample executable

### ISSUE THREAD

**Issue by danielmateos99** [mgbellemare/Arcade-Learning-Environment#414]
I am trying to include some .hpp files in the videorecording.cpp example. I tried to modify the build.make file including the paths needed, but after compiling the videorecording executable, it still fails finding the paths.

Photo of the build.make file modified with the paths:

![imagen](https://user-images.githubusercontent.com/63020032/116820422-53c6e880-ab75-11eb-9d61-c9da06f8ac04.png)

**Comment by JesseFarebro** [comment]
You shouldn't modify the `*.make` files directly. I'd recommend searching for how to include files using CMake then include your files directly from the `CMakeLists.txt` file in the video recording example folder.
