### ISSUE TITLE
Random environment

### ISSUE THREAD

**Issue by Adrii98** [mgbellemare/Arcade-Learning-Environment#418]
Hi 
How can i initialize randomly the environment each time i run ale
What i want to do is to play a game and after it finishes restart it but with another environment so the game will be different.

**Comment by JesseFarebro** [comment]
The only form of stochasticity provided by the ALE is through sticky actions, i.e., there's a probability the current action you want to take will be replaced by the previously executed action. The environment itself won't change and there's no way to do this. Atari games are largely deterministic and the remaining that have their own PRNG are controlled for in the emulator so they as well are deterministic. (see #401 for more info)
