### ISSUE TITLE
CartridgeUA::patch only updates first address in memory bank

### ISSUE THREAD

**Issue by Weverything** [mgbellemare/Arcade-Learning-Environment#419]
In Arcade-Learning-Environment/src/emucore/CartUA.cxx, the function CartridgeUA::patch

```
bool CartridgeUA::patch(uint16_t address, uint8_t value)
{
  address &= 0x0fff;
  myImage[myCurrentBank * 4096] = value;
  bank(myCurrentBank); // TODO: see if this is really necessary
  return true;
} 
```
Since address isn't used to decide the memory address, value is always written to the first first location of the current bank.  It should be:

```
  myImage[myCurrentBank * 4096 + address] = value;
```

This was detected by clang warning -Wunused-but-set-parameter.  If the code is correct as-is, then the line 'address &= 0x0fff;' should be removed as it does not affect anything.

**Comment by tkoeppe** [comment]
@mgbellemare: Could you kindly take a look? If this is a real bug, we'd be keen on importing the fix.

**Comment by JesseFarebro** [comment]
Good catch, this is a bug from the version of Stella the ALE uses. This issue was fixed upstream here: https://github.com/stella-emu/stella/commit/79e4e42ae755eb77994b88c3173df1babd01185f#diff-b826c30b083db909de2492a92e68832b4a9f169307b65271cea40a6f8182eb27R182.

I've adopted this change in #420.

**Comment by tkoeppe** [comment]
Brilliant, thanks!
