### ISSUE TITLE
Natively support CUDA/TPU execution

### ISSUE THREAD

**Issue by jkterry1** [mgbellemare/Arcade-Learning-Environment#423]
This is a request for the fairly distance future, but ideally the ALE would be able to natively run on CUDA/TPUs/etc. in addition to CPUs in the same vein as brax. https://github.com/NVlabs/cule already got it to work on CUDA at least, though this was a hard fork and appears to never have been seriously maintained.

**Comment by JesseFarebro** [comment]
As [envpool](https://github.com/sail-sg/envpool) has shown it's much more efficient to run the emulator on CPU. There are still lots of performance improvements that can be made here. One of the immediate things we're working on is moving the entire preprocessing stack into C++ to save on memory copies & memory fragmentation. This should provide a noticeable improvement in performance.
