### ISSUE TITLE
Cloning @5e3c3c1 commit as part of another repo

### ISSUE THREAD

**Issue by AvivSham** [mgbellemare/Arcade-Learning-Environment#424]
Hi All,
I'm trying to install the [following repo (Facebook Rela)](https://github.com/facebookresearch/rela/tree/main/atari) which relay on your repo. The submodule is looking at your @5e3c3c1 commit but for some reason, the recursive clone fails when it comes to cloning your repo. This is the error:
```ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:mgbellemare/Arcade-Learning-Environment.git' into submodule path 'atari/Arcade-Learning-Environment' failed
 ```

as a workaround I can clone the repo without the recursive flag and manually add your repo to the desired location, I just don't know if Rela supports your latest commit.

@AvivNavon
Please help :)

**Comment by JesseFarebro** [comment]
The commit exists: https://github.com/mgbellemare/Arcade-Learning-Environment/tree/5e3c3c1

This seems to be a problem with their submodules specifying the repositories using SSH. It seems it tries to authenticate regardless of the repository (I'm not sure why this is the default, I can't find any info on this). Their repository fails to clone pybind11 as well. You can change the submodules to use https and it works fine.
