### ISSUE TITLE
Video in Readme.md is currently unviewable

### ISSUE THREAD

**Issue by sparr1** [mgbellemare/Arcade-Learning-Environment#428]
Due to the YouTube video being private, the [link](https://www.youtube.com/watch?v=nzUiEkasXZI) to the video showing off the games supported is not useful. It would be helpful to either make the video public so we can see it, or update the readme to point somewhere else or say something else otherwise. Thanks!

**Comment by JesseFarebro** [comment]
Thanks for reporting this @sparr1. The video should now be public again.
