### ISSUE TITLE
render_mode is unavailable in gym.make

### ISSUE THREAD

**Issue by DhruvaKashyap** [mgbellemare/Arcade-Learning-Environment#429]
The render_mode kwarg is no longer supported in the .make() method, would it be advisable to use .render(mode="human") instead?

**Comment by JesseFarebro** [comment]
Can you elaborate on this? You're using gym>=0.20 and ale-py>=0.7 and you're not able to use render_mode?

**Comment by DhruvaKashyap** [comment]
It seems that I had some issues with the version of gym. I was using gym 0.19.0 and was unable to use render_mode. Upgrading to gym 0.20 has fixed that.
Sorry for confusion, this issue can be closed.
