### ISSUE TITLE
Targets for SDL not found

### ISSUE THREAD

**Issue by DarthMalloc** [mgbellemare/Arcade-Learning-Environment#430]
I am trying to install ALE with SDL support on a Linux Mint 19.3 system, and I am getting the following error:

``` CMake Error at src/CMakeLists.txt:62 (add_library):
  Target "ale-lib" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an  ALIAS target is missing?```

```CMake Error at src/python/CMakeLists.txt:10 (add_library):
  Target "ale-py" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?```

```CMake Error at src/CMakeLists.txt:23 (add_library):
  Target "ale" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?```

```CMake Error at src/CMakeLists.txt:62 (add_library):
  Target "ale-lib" links to target "SDL2::SDL2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?```


I made sure that sdl2 is installed, so I am not clear on what the problem is. Any help would be much appreciated.

**Comment by JesseFarebro** [comment]
Hi @DarthMalloc,

It's really hard for me to debug all these edge cases with search paths on different systems. What I can recommend is using [vcpkg](https://github.com/microsoft/vcpkg) to manage your dependencies. This is how we the ALE for distribution and our infrastructure is set up to work with vcpkg.

If this isn't something you want to do I can try to help you debug this issue. Are you specifying the config `SDL_DYNLOAD`? This should be set to `OFF` if you want to link locally to your copy of SDL.

**Comment by JesseFarebro** [comment]
No, not locally. The general way you should do it looks like:

```
# Download vcpkg to some local folder not inside the ALE, e.g., ~/.local/share
git clone https://github.com/Microsoft/vcpkg ~/.local/share/vcpkg

# Download vcpkg
cd ~/.local/share/vcpkg
./bootstrap-vcpkg.sh

# Export the variables we need to pick up on, probably put these in ~/.bashrc, ~/.zshrc, etc.
export VCPKG_ROOT=~/.local/share/vcpkg
export VCPKG_DEFAULT_TRIPLET=x64-linux

# Download the necessary dependencies
vcpkg install zlib sdl2

# Download and build ALE
cd ~/Desktop
git clone https://github.com/mgbellemare/Arcade-Learning-Environment
cd Arcade-Learning-Environment

mkdir build && cd build
cmake ../  \
    -DSDL_SUPPORT=ON \
    -DSDL_DYNLOAD=OFF \
    -DBUILD_PYTHON_LIB=OFF \
    -DCMAKE_BUILD_TYPE=Release
cmake --build . --parralel 16 # or how many CPU cores you have
cmake --build . --target install # Installs ALE locally to your machine
```

Now the ALE is installed locally, you can link against the `ale::ale-lib` target using CMake. Check out the examples in `examples/cpp-interface`.

**Comment by DarthMalloc** [comment]
I deleted the vcpkg directory, remade it, and reinstalled the sdl2 and zlib packages according to your instructions, but I still get the same error. When I enter gcc --version, I get

`gcc (Ubuntu 11.1.0-1ubuntu1~18.04.1) 11.1.0`

So it seems I have the correct compiler version.

What could the problem be?

**Comment by JesseFarebro** [comment]
Did you manage to solve this issue?

**Comment by DarthMalloc** [comment]
Hi @JesseFarebro, this one has been resolved, however I seem to be having a different problem now.
