### ISSUE TITLE
Inclusion of Implementations of Feature Generation Algorithms from Bellemare et al. (2013)

### ISSUE THREAD

**Issue by DarthMalloc** [mgbellemare/Arcade-Learning-Environment#432]
Would it be possible to include the python implementations of the feature generation algorithms, such as the BASS and BASIC methods, from the Bellemare et al. (2013) paper? It would be of great help in experiments involving ALE.

**Comment by JesseFarebro** [comment]
We don't provide these feature extraction methods but one place to look for these is in Marlos Machado's work, e.g., https://github.com/mcmachado/ALEResearch/tree/master/src/features (has some of the original feature extraction algorithms), https://github.com/mcmachado/b-pro (builds on the original features in this work: https://arxiv.org/abs/1512.01563). I hope this helps.
