### ISSUE TITLE
Improve documentation on how install gym and ROMs

### ISSUE THREAD

**Issue by apacha** [mgbellemare/Arcade-Learning-Environment#437]
I just wasted more than an hour trying to figure out how to get my old gym samples up and running with the changed ROM loading mechanism. I think it would be great if you could do future visitors/developers the favor and add the following information to the README:

- Make sure that you're installing gym>=0.21.0
- Install gym by calling `gym[atari,accept-rom-license]==0.21.0` as stated [here](https://github.com/openai/gym/releases/tag/v0.21.0).

Similarly, for users of Google Colab, these commands might be helpful too:

```
# Download and extract ROMs automatically
!wget http://www.atarimania.com/roms/Roms.rar
!mkdir /content/ROM/
!unrar e /content/Roms.rar /content/ROM/
!python -m atari_py.import_roms /content/ROM/

# Show all ROMs
import ale_py.roms as roms
print(roms.__all__)

# Now all ROMs can be used normally
from ale_py import ALEInterface
from ale_py.roms import Pong
pong_rom = ale.loadROM(Pong)
```

**Comment by JesseFarebro** [comment]
Gym chooses to provide the `accept-rom-license` extra. This is a tool that works with the new ALE ROM plugin system. This isn't something we actively support, any package can export ROMs to the ALE, we aren't going to document them all.

I believe Gym is trying to upgrade their documentation but until then you could open an issue with Gym for visibility.

Furthermore, I would not suggest for people to use your instructions for Colab. We won't support discovering ROMs in the `atari-py` package in the future. The suggested method is to download ROMs and use the `ale-import-roms` CLI tool as documented in the README: https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management.

For additional info about these changes, you can see the blog post for the 0.7 release: [https://brosa.ca/blog/ale-release-v0.7](https://brosa.ca/blog/ale-release-v0.7)
