### ISSUE TITLE
Frame post-processing for reproducing the nature DQN.

### ISSUE THREAD

**Issue by alirahkay** [mgbellemare/Arcade-Learning-Environment#439]
What is your suggestion for doing frame-postprocessing (taking the max over two grayscaled frames) similar to what [Dopamine](https://github.com/google/dopamine/blob/df97ba1b0d4edf90824534efcdda20d6549c37a9/dopamine/discrete_domains/atari_lib.py#L329-L515) is doing?
The solution in their repo would impose setting the frame-skip equal to one in the v5 version of the ale and then implementing the frame-skip manually! Is this the best practice?

**Comment by JesseFarebro** [comment]
Hi @alirahkay,

Yes, I'd suggest doing post-processing exactly how Dopamine is doing so. I've thought about moving frame maxing into the ALE itself (we have support for averaging successive frames) but maxing introduces other issues. Ideally, we would update the colour averaging algorithm to replace frame maxing but we haven't gotten around to this (#101).

So as you said, if you're using v5 environments you should create them via,
```py
env = gym.make('ALE/Breakout-v5', frameskip=1)
env = AtariPreprocessing(env)
```

In the future, the Gym Atari wrapper might be factored out of Gym and at that point, it might be possible to make this easier for Gym users.
