### ISSUE TITLE
BattleZone

### ISSUE THREAD

**Issue by slerman12** [mgbellemare/Arcade-Learning-Environment#444]
I am getting this:

`RuntimeError: Invalid game mode requested`

For `ALE/BattleZone-v5`.

**Comment by slerman12** [comment]
Other games work, just this one is a choke point for some reason

**Comment by JesseFarebro** [comment]
Hi @slerman12,

I'm unable to reproduce this issue. Could you give me more information on your setup? This error probably stems from passing the `mode` kwarg to the `gym.make` constructor. If you are doing this you should note that there is no universal default mode, i.e., mode 0 won't be available on every game. You should pass `mode=None` if you want the default game mode.

**Comment by slerman12** [comment]
Thanks, I removed the gym mode parameter. Hopefully that's equivalent to setting it to None
