### ISSUE TITLE
Installation issue: Package not found ale-py

### ISSUE THREAD

**Issue by jaiswalharsh** [mgbellemare/Arcade-Learning-Environment#447]
I have tried many hours to find a way to install ale-py but no luck. I have been trying to run OpenAI gym with Atari dependency and cannot go forward without installing _ale-py_

pip install gym[all]  OR pip install ale-py both throw the following error which I can't seem to solve.

`Collecting ale-py
  Could not find a version that satisfies the requirement ale-py (from versions: )
No matching distribution found for ale-py
`

I am running Ubuntu 18.04 and using python version 3.6.9.

Any help would be appreciated.

**Comment by JesseFarebro** [comment]
Hi, can you give me the details of your system? What OS? What Python version?

**Comment by jaiswalharsh** [comment]
> Hi, can you give me the details of your system? What OS? What Python version?

I have updated the issue description with the details.

**Comment by jaiswalharsh** [comment]
Also for more specific details running _pip install gym[atari]_ tries to find a specific version of _ale-py==0.7.1_

**Comment by JesseFarebro** [comment]
So you won't be able to download the latest version of ale-py because Python 3.6 is deprecated as of December 2021. You can still try to download 0.7.1 which did publish 3.6 binaries. Try,

```
pip install ale-py==0.7.1
```

Also, make sure pip is up to date or the above might fail.

**Comment by jaiswalharsh** [comment]
It worked! I upgraded pip using: `pip install --upgrade pip`

Thank you for your fast reply! :)
