### ISSUE TITLE
Frameskip = 0 makes no sense 

### ISSUE THREAD

**Issue by BenedictWilkins** [mgbellemare/Arcade-Learning-Environment#449]
When making a new environment with `frameskip = 0`  the environment state will remain at the initial state after any number of steps.
```
env = gym.make("ALE/SpaceInvaders-v5", frameskip=0)
```
I wasted some time on this, better to give an error -- i.e. assert frameskip > 0
I can't think of any situation when someone would want this behaviour.

**Comment by JesseFarebro** [comment]
Thanks for pointing this out. The ALE interface does account for this but the Gym interface manages frame skipping itself. I'll make sure to make this more clear in the upcoming release.

**Comment by JesseFarebro** [comment]
This is fixed in beb8d8ec6cdf5d11f079b6cd22003c39625ba04f.
