### ISSUE TITLE
SDL/SDL.h not found when compiling with cmake -DUSE_SDL=ON

### ISSUE THREAD

**Issue by mgbellemare** [mgbellemare/Arcade-Learning-Environment#45]
MacPorts installs SDL in /opt/local/include/SDL. CMake correctly finds the library, and adds 

-I/opt/local/include/SDL

to the include path used to compile ALE. However, a number of files include "SDL/SDL.h" (rather than SDL), and so building with SDL enabled fails on my machine.

Suggested fix: directly include "SDL.h" and fix the include paths in makefile.mac/unix accordingly.

**Comment by mhauskn** [comment]
SGTM. Once you push this change, I'll test on my Brew installed SDL to make sure things are still working on my end.

**Comment by mgbellemare** [comment]
I've pushed the change. Let me know if it breaks anything on your side.

**Comment by mhauskn** [comment]
Everything works well on my side.
