### ISSUE TITLE
RuntimeError: Failed to initialize SDL

### ISSUE THREAD

**Issue by dyllanwli** [mgbellemare/Arcade-Learning-Environment#451]
[Environments]: 
+ python 3.8.3
+ ale-py==0.7.4
+ gym[accept-rom-license]==0.22.0
+ gym[atari]

[Reproduce]:
```
import ale_py
import gym
env = gym.make('ALE/FishingDerby-v5', render_mode='human')
```
Then I got runtime error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-26044f6f8f13> in <module>
----> 1 env = gym.make('ALE/FishingDerby-v5', render_mode='human')

~/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py in make(id, **kwargs)
    674 # fmt: on
    675 def make(id: str, **kwargs) -> "Env":
--> 676     return registry.make(id, **kwargs)
    677 
    678 

~/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py in make(self, path, **kwargs)
    518         spec = self.spec(path)
    519         # Construct the environment
--> 520         return spec.make(**kwargs)
    521 
    522     def all(self):

~/miniconda3/lib/python3.8/site-packages/gym/envs/registration.py in make(self, **kwargs)
    138         else:
    139             cls = load(self.entry_point)
--> 140             env = cls(**_kwargs)
    141 
    142         # Make the environment aware of which spec it came from.

~/miniconda3/lib/python3.8/site-packages/gym/envs/atari/environment.py in __init__(self, game, mode, difficulty, obs_type, frameskip, repeat_action_probability, full_action_space, render_mode)
    121 
    122         # Seed + Load
--> 123         self.seed()
    124 
    125         self._action_set = (

~/miniconda3/lib/python3.8/site-packages/gym/envs/atari/environment.py in seed(self, seed)
    178                 "https://github.com/mgbellemare/Arcade-Learning-Environment#rom-management"
    179             )
--> 180         self.ale.loadROM(getattr(roms, self._game))
    181 
    182         if self._game_mode is not None:

RuntimeError: Failed to initialize SDL
```
I was trying to add human render mode to my research to use `env.render()`

**Comment by blackwint3r** [comment]
Have the same problem under Mac m1! 
Here is my test code:

```
from ale_py import ALEInterface, SDL_SUPPORT
ale = ALEInterface()
ale.setInt("random_seed", 123)
if SDL_SUPPORT:
    ale.setBool("sound", True)
    ale.setBool("display_screen", True)
from ale_py.roms import Breakout
ale.loadROM(Breakout)  # <--   RuntimeError: Failed to initialize SDL

```

**Comment by JesseFarebro** [comment]
@dyllanwli what platform are you running on? Arm as well?

**Comment by Senhongl** [comment]
Same issue on my Mac M1 chip as well.

**Comment by JesseFarebro** [comment]
Hmm, okay, would someone be willing to test some custom wheels I'll upload to https://test.pypi.org/? I don't have access to an M1 machine and I have no way of testing this. I blindly decided to build the ARM wheels for macOS but I guess there are some issues after all 😞 .

**Comment by turboka11e** [comment]
I had the same issue with M1 but solved the issue by replacing the "libSDL2-2.0.dylib" in the site package from ale-py with another one. I replaced it with the "libSDL2-2.0.0.dylib" (Notice: slightly different name needs to be changed) from the site-package pygame. However the problem did not occur on all ARM machines, for example on Jetson AGX Developer Kit, which runs ARM Ubuntu 18.04.

**Comment by turboka11e** [comment]
> Hmm, okay, would someone be willing to test some custom wheels I'll upload to https://test.pypi.org/? I don't have access to an M1 machine and I have no way of testing this. I blindly decided to build the ARM wheels for macOS but I guess there are some issues after all 😞 .

I could test it. I have an M1 Pro (MacBook Pro 16")

**Comment by JesseFarebro** [comment]
@turboka11e that's very unusual. So you're saying that renaming the file `libSDL2-2.0.dylib` to `libSDL2-2.0.0.dylib` inside of the ALE's site-packages folder fixed this issue? When we build the Python wheels we specifically give the filename of the dynamic library before we copy it (https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/python/CMakeLists.txt#L65). I can't imagine why there would be this mismatch.

I'll put together a test wheel that has extra debugging info so we can get to the bottom of this. I'll update this post once I've published it to PyPi test.

**Comment by turboka11e** [comment]
@JesseFarebro Sorry, that's not what I've meant. I was replacing the original **libSDL2-2.0.dylib** from another package [pygame](https://github.com/pygame), as a hotfix to get it working. But they would name it slightly different, hence that's why I needed to change the name. So the problem is not a matching error, but must be something else.
Alright perfect, I'll wait for the update. 👍🏼

**Comment by JesseFarebro** [comment]
@turboka11e can you try this build: https://test.pypi.org/project/ale-py/0.7.5/. Simplily:

```sh
pip install -i https://test.pypi.org/simple/ ale-py==0.7.5
```

**Comment by JesseFarebro** [comment]
Sorry about that, you can now download 0.7.5 from the main PyPi repository. Let me know if that fixes this problem! Thanks for helping test this out 😄.

**Comment by turboka11e** [comment]
Hurray - it works!

My script to test it:

```
import gym

env = gym.make('ALE/Breakout-v5', render_mode='human')

env.reset()
for _ in range(1000):
    env.step(env.action_space.sample())
env.close()
```

Thanks a lot :) @JesseFarebro
