### ISSUE TITLE
OSError: [WinError 127]

### ISSUE THREAD

**Issue by whliu90** [mgbellemare/Arcade-Learning-Environment#452]
`>>> from ale_py import ALEInterface`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\whliu\.conda\envs\rl\lib\site-packages\ale_py\__init__.py", lin
e 26, in <module>
    os.add_dll_directory(packagedir)
  File "C:\Users\whliu\.conda\envs\rl\lib\os.py", line 1109, in add_dll_director
y
    cookie = nt._add_dll_directory(path)
OSError: [WinError 127] 找不到指定的程序。: 'C:\\Users\\whliu\\.conda\\envs\\rl\
\lib\\site-packages\\ale_py'

- python 3.8.8
- win 64

**Comment by JesseFarebro** [comment]
Hmm, this doesn't seem to be an issue with the ALE. Could you try just running:

```py
import os

os.add_dll_directory(os.getcwd())
```
and tell me if it gives you an error.

I think this might be an issue with Conda. You can try running the ALE without Conda and this may solve your issue.

**Comment by whliu90** [comment]
> 

Yeah, it seems you are right. When I try running:
```
import os
os.add_dll_directory(os.getcwd())
```
, I get a similar error: "OSError: [WinError 127]". Could you give me some advice to fix it? Thanks.

**Comment by JesseFarebro** [comment]
I'm sorry but I've never used Windows so I'm unsure on what this error could mean. As I mentioned before, I'd recommend trying to use the ALE outside of Conda. There can be some weird issues that crop up sometimes, we also only test on the main Python distribution, not Conda.
