### ISSUE TITLE
How to Disable Logging on Gym Environment Initialization?

### ISSUE THREAD

**Issue by Hamptonjc** [mgbellemare/Arcade-Learning-Environment#456]
I get:
```python
e = gym.make("ALE/Breakout-v5")
```
```bash
A.L.E: Arcade Learning Environment (version 0.7.5+db37282)
[Powered by Stella]
```

I want:
```python
e = gym.make("ALE/Breakout-v5")
```

With no logging output. 

Seems I need access to the ALEInterface object before I can reduce the logging level. 

How can I do this so that I don't get the logged output on gym.make()?

**Comment by floringogianu** [comment]
I'm doing something along the lines of:

```python
from ale_py import ALEInterface, LoggerMode

ale = ALEInterface()
ale.setLoggerMode(LoggerMode.Error)
```

Hope this helps!

**Comment by JesseFarebro** [comment]
Yes, @floringogianu is correct. You can make one slight modification though. `setLoggerMode` is a class method so you can:

```py
from ale_py import ALEInterface, LoggerMode

ALEInterface.setLoggerMode(LoggerMode.Error)
```
and you won't get any output when constructing the ALE.
