### ISSUE TITLE
`env.ale.setRAM( )` does not change internal state

### ISSUE THREAD

**Issue by richcmwang** [mgbellemare/Arcade-Learning-Environment#465]
While `setRAM` effect can be seen when running `getRAM`, it does not change the internal state.  Specifically, we can see from the following steps:

0. run `env.ale.getRAM( )[51]`,  the result is 72
1. run  `env.ale.setRAM(51, 100)`
2. run `env.ale.getRAM( )[51]`, the result is 100
3. run `env.step(0)` 
4. run `env.ale.getRAM( )[51]`, the result goes back to 72

Is this a bug?  Any other possible way to change the internet state?

**Comment by JesseFarebro** [comment]
Hi @richcmwang, I actually just responded to your inquiry via email so hopefully that solves your issue.
