### ISSUE TITLE
Small question about gym defaults

### ISSUE THREAD

**Issue by slerman12** [mgbellemare/Arcade-Learning-Environment#470]
One of the options when running `gym.make` is `difficulty`:

`env = gym.make('ALE/Breakout-v5', difficulty=0)`

I noticed that this argument setting works for most tasks, but not Backgammon for example. Can I just leave `difficulty` blank and assume that the default will be the easiest, or is that assumption not true for some envs?

**Comment by slerman12** [comment]
Also, unrelated question: What is the Mario Bros. that comes with Atari? Is it different from the Super Mario Bros from `pip install gym-super-mario-bros==7.3.0`?

**Comment by JesseFarebro** [comment]
Hi @slerman12, there is no default difficulty, if you don't want to specify a difficulty you should set `difficulty=None` (this is the default).

Although it seems there was a version of the original Mario Bros ported to the Atari 2600 we don't support this. The Super Mario Bros package you linked uses an NES emulator.
