### ISSUE TITLE
Environment Breakout doesn't exist in namespace ALE. 

### ISSUE THREAD

**Issue by francesco-taioli** [mgbellemare/Arcade-Learning-Environment#473]
Hi,
I get this error in a new Colab environment : `Environment Breakout doesn't exist in namespace ALE. `

**Steps to reproduce**
```
import gym
print(gym.__version__)
gym.make("ALE/Breakout-v5") # <--- fail here
```

The gym version is `0.25.2`. ALE should be inside gym

I looked at this doc: [gym api Breakout](https://www.gymlibrary.dev/environments/atari/breakout/)

**Comment by JesseFarebro** [comment]
Hi @francesco-taioli,

It's likely that you hadn't installed any ROMs. The ALE doesn't ship with ROMs and you'd have to install them yourself. If you had already installed them I'd need some more info to help debug this issue. Let me know if you're still encountering this issue within Colab and I can try to assist further.
