### ISSUE TITLE
Speed-up rendering 

### ISSUE THREAD

**Issue by andrewrona** [mgbellemare/Arcade-Learning-Environment#474]
Hello,

I was wandering if it could be possible to speed-up the ALE game window when selecting `render_mode = 'human'`
Sometimes one episode is very long, and it is very time-consuming watching without speeding up the frames. 

Thank you for your reply.

**Comment by JesseFarebro** [comment]
Hi @andrewrona,

You can increase and decrease the framerate when using `render_mode = 'human'`. Make sure the render window is selected and then hit your keyboard's left or right arrow. This will either decrease or increase the FPS respectively. Also, the up and down arrow will adjust the volume accordingly.

Hope this helps!
