### ISSUE TITLE
Can't install on CentOS 7

### ISSUE THREAD

**Issue by vmoens** [mgbellemare/Arcade-Learning-Environment#478]
When installing 0.8.0 with python 3.10 on a CentOS 7 machine, only the versions < 0.8 are found by pip.
I tried downloading the wheels:
```
$ pip install ale_py-0.8.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
ERROR: ale_py-0.8.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
```

If i rename the wheels to 
```
ale_py-0.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
the installation goes fine.
This name is similar to the 0.7.5 release (I just changed the version in the filename).

I guess this bug could be fixed by simply changing the wheel names by hand before twining it on pypi.

**Comment by JesseFarebro** [comment]
Hi @vmoens,

This is on purpose to support some modern C++ features. You can check out the manylinux spec here: https://github.com/pypa/manylinux to learn more about how tagging works. To give a brief recap:

- `manylinx_MAJOR_MINOR` corresponds to the MAJOR.MINOR version of glibc that's supported by that wheel. Not being able to install 2_27 means that PyPi has determined your OS doesn't support this tag (hence this version of glibc) and refuses to install it.
- It is possible to change the tag but there's no guarantee of backwards compatibility.

As CentOS 7 is coming up on EOL next year and I haven't received any other complaints I'll probably be sticking with manylinux_2_28. You can always solve this problem by using Conda which manages its own version of glibc.

**Comment by JesseFarebro** [comment]
I investigated a little further and decided to revert back to manylinux2014 (i.e., glibc 2.17). As of v0.8.1 you shouldn't have any issues on CentOS 7.
