### ISSUE TITLE
Videochess, Videocube and TicTacToe3D don't work

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [mgbellemare/Arcade-Learning-Environment#480]
The `ale_py.roms.utils.rom_name_to_id` doesn't correctly convert the environment name for video chess, video cube and tic-tac-toe-3d.

```python
env_names=['TicTacToe3D', 'Videochess', 'Videocube']
converted_ids=['tic_tac_toe3_d', 'videochess', 'videocube']  # [rom_utils.rom_name_to_id(name) for name in env_names]
actual_rom_ids=['tic_tac_toe_3d', 'video_chess', 'video_cube']
```

As a result `gym.make("ALE/TicTacToe3D-v5")` raises issue, same with `Videochess` and `Videocube`.

**Comment by JesseFarebro** [comment]
This should now be fixed in v0.8.1.
