### ISSUE TITLE
Strict TDQM requirement

### ISSUE THREAD

**Issue by slerman12** [mgbellemare/Arcade-Learning-Environment#488]
This ale-py package requires a strict version of tdqm. Is that necessary? I'm having trouble getting this package to not conflict with other ones. Alternatively, I could use 0.7.5, but that version isn't installable through pip unless I use an older python version I guess.

**Comment by JesseFarebro** [comment]
Hi @slerman12, I'm a little confused, `ale-py` doesn't depend on tqdm? These are our dependencies: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/pyproject.toml#L36-L39 none of which have strict versioning requirements.

**Comment by slerman12** [comment]
Sorry, the issue was with nes-py. And I resolved it anyway. Thanks!
