### ISSUE TITLE
SDL/SDL.h not found when compiling with cmake -DUSE_SDL=ON

### ISSUE THREAD

**Issue by mgbellemare** [mgbellemare/Arcade-Learning-Environment#52]
CMake does not always include the parent path of the SDL directory. The fix is to #include <SDL.h> instead.

**Comment by mhauskn** [comment]
Here is the summary of SDL includes in the current codebase:
```
./doc/examples/sharedLibraryInterfaceExample.cpp:21:  #include <SDL.h>
./src/emucore/SpeakJet.hxx:85:#include <SDL.h>
./src/common/SoundSDL.hxx:26:#include <SDL/SDL.h>
./src/common/display_screen.h:28:#include "SDL/SDL.h"
./src/common/SoundSDL.cxx:24:#include <SDL/SDL.h>
```

So it looks like we have a mix of <SDL.h> and <SDL/SDL.h>. 

Also, we should change the display_screen.h include to use brackets instead of quotes. This may be the culprit.

**Comment by mgbellemare** [comment]
The quotes isn't the culprit, unfortunately. On a related note, SpeakJet
isn't used by ALE (it has to do with the AtariVox), so we could consider
chucking it out.

**Comment by mgbellemare** [comment]
Do we feel this is resolved?

**Comment by mhauskn** [comment]
Using -sdl-config to generate the include paths has solved this issue.
