### ISSUE TITLE
Stochasticity Parameter (repeat_prob) is fixed in the code

### ISSUE THREAD

**Issue by mcmachado** [mgbellemare/Arcade-Learning-Environment#56]
We have implemented the stochasticity in stella_environment.cpp, and the stochasticity parameter is set in the variable repeat_prob. However, it is not a parameter we can set using flags, but something written in the code and to change it we need to change the default value and then re-compile the ALE. We should probably make a flag to it.

**Comment by mhauskn** [comment]
Agreed. Some possible names for the flag: repeat_prob, stochasticity, action_repeat_prob

**Comment by mcmachado** [comment]
I am going to close this issue, since my code fixing it was merged.
