### ISSUE TITLE
Is it possible to modify the games?

### ISSUE THREAD

**Issue by anguyen8** [mgbellemare/Arcade-Learning-Environment#64]
Hello Marc,

Thanks much for putting out this great source code. I know this is an emulator platform. 
I'd like to ask if it is possible to modify the games (e.g. size/shape of characters, frequency of appearance of enemy objects) slightly in some way using this source code?

I greatly appreciate your answer.

Best,

Anh

**Comment by mgbellemare** [comment]
Hi Anh,

Good question! I would say it's probably fairly difficult to change the game code itself, unless you're familiar with Atari 2600 programming. This said, there is an active community online (see, e.g., 
http://www.atari2600homebrew.com/ ) that creates new Atari 2600 games, so you could
look there for answers. Some simple changes should certainly be possible.

Alternatively, you could write code to modify the RAM on the fly (e.g. remove enemies when
they appear), although your mileage may vary.

There is also an ALE mailing list at

https://groups.google.com/forum/#!forum/arcade-learning-environment

which you can more directly ask questions to.

Cheers,
- Marc

**Comment by anguyen8** [comment]
@mgbellemare : Marc, awesome pointers. I appreciate your reply!
