### ISSUE TITLE
odd makefile.mac include

### ISSUE THREAD

**Issue by mhauskn** [mgbellemare/Arcade-Learning-Environment#69]
makefile.mac links against the directory /opt/local/lib. This directory doesn't exist on my machine and results in an error when building. Is this line necessary?:

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/makefile.mac#L16

**Comment by mgbellemare** [comment]
It's needed by some MacPort-based installs. It doesn't seem to be anymore (at least not on my Mac). I'm happy to remove the offending -L/opt/local/lib, and add a comment just above the LIBS definition mentioning MacPort users may need to add -L/opt/local/lib back in. This said, I never expect makefile.mac to work out of the box...

**Comment by mhauskn** [comment]
Okay I'm happy as long as it is useful for some users. Perhaps this will also encourage people to start building with cmake.
