### ISSUE TITLE
Screen Display works with C++ interface, but not with Python interface

### ISSUE THREAD

**Issue by DoctorTeeth** [mgbellemare/Arcade-Learning-Environment#71]
Hi, thanks for this project! I have the following issue:

I installed the most current version of ALE on a box running Ubuntu 14.04.
I am using Python 2.7.6. 
I built with cmake as described in the manual (with the use SDL flag set to true) and ran `pip install .` in the root directory of the project. 

cding to doc/examples and executing `python python_example.py breakout.bin` works as advertised.
However, changing line 23 to `USE_SDL = True` yields the following runtime error:

Screen display requires directive __USE_SDL to be defined. Please recompile with flag '-D__USE_SDL'. See makefile for more information.

This is being thrown from ./src/emucore/OSystem.cxx, according to grep.
It comes from the following block:
`
#ifndef __USE_SDL
    std::cerr << "Screen display requires directive __USE_SDL to be defined."
              << " Please recompile with flag '-D__USE_SDL'."
              << " See makefile for more information."
              << std::endl;
    exit(1);
#endif
`

I thought this might have something to do with cmake not playing nicely with SDL, but sharedLibraryInterfaceExample runs with no issues (so I think I can rule that out?). 

I will keep looking at this, and I'm sure I'll be able to find some sort of resolution by messing with the ale_python interface to get it to define __USE_SDL, but I raise this issue because I expect that you guys would like this to work out of the box.

**Comment by mhauskn** [comment]
If sdl wasn't enabled the first time you installed the
ale-python-interface, you'll need to uninstall it and reinstall after
building ale with sdl enabled.

**Comment by DoctorTeeth** [comment]
Indeed, I glossed over the following message last time:

augustus@super1:~/Arcade-Learning-Environment$ sudo pip install .
Unpacking /home/users/augustus/Arcade-Learning-Environment
  Running setup.py (path:/tmp/pip-6Zqwz1-build/setup.py) egg_info for package from file:///home/users/augustus/Arcade-Learning-Environment
    
  Requirement already satisfied (use --upgrade to upgrade): ale-python-interface==0.0.0 from file:///home/users/augustus/Arcade-Learning-Environment in /usr/local/lib/python2.7/dist-packages
Cleaning up...

forcing pip to upgrade fixed this issue. 

Thanks for the help.
