### ISSUE TITLE
Colour Averaging default option has changed

### ISSUE THREAD

**Issue by mcmachado** [mgbellemare/Arcade-Learning-Environment#72]
In version 0.4 the Colour Averaging parameter was set as true by default. Currently it is being set as false by default. This is bad because it does not give us backward compatibility. 

I will fix this as soon as you agree with this that this has to be changed (I messed it up). I received complaints about people getting worse results in the new version and I assume it is because of this.

**Comment by mgbellemare** [comment]
Go ahead. Let's keep track of these behaviour-changing fixes in the changelog & add a notice to README.md pointing to the changelog.

**Comment by mcmachado** [comment]
Fixed. I also added it to the ChangeLog file.
