### ISSUE TITLE
Build failing on Windows (msys)

### ISSUE THREAD

**Issue by Jragonmiris** [mgbellemare/Arcade-Learning-Environment#78]
I've been trying to build the ALE on msys. I fixed a few small compilation errors, which you can see by looking at the diffs on my fork:

https://github.com/Jragonmiris/Arcade-Learning-Environment

It mostly just involved explicitly including <time.h> in a couple places, and deleting an argument to mkdir.

However, I'm getting the following linker error for ale.exe

    CMakeFiles/ale-bin.dir/objects.a(ale_interface.cpp.obj):ale_interface.cpp:(.text+0x5cf): undefined reference to `OSystemWin32::OSystemWin32()'
    CMakeFiles/ale-bin.dir/objects.a(ale_interface.cpp.obj):ale_interface.cpp:(.text+0x5fd): undefined reference to `SettingsWin32::SettingsWin32(OSystem*)'
    collect2.exe: error: ld returned 1 exit status
    CMakeFiles/ale-bin.dir/build.make:3509: recipe for target '../ale.exe' failed
    make[2]: *** [../ale.exe] Error 1
    CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/ale-bin.dir/all' failed
    make[1]: *** [CMakeFiles/ale-bin.dir/all] Error 2
    Makefile:75: recipe for target 'all' failed
    make: *** [all] Error 2

The makefile was generated with -G "MSYS Makefiles". I'm not sure where to proceed from here, perhaps there are some defines somewhere that are being wonky? Because it seems like the object files for the windows systems likely aren't being built.

**Comment by pkulchenko** [comment]
@Jragonmiris, I ran into the same issue and fixed it by changing `if(WINDOWS)` to `if(WINDOWS OR MINGW)` in `CMakeLists.txt`. Otherwise the makefile compiles Unix/POSIX version instead of the Windows one and that's why the linking step fails.
