### ISSUE TITLE
OS X 10.10 make error

### ISSUE THREAD

**Issue by udibr** [mgbellemare/Arcade-Learning-Environment#80]
I'm following the manual instructions for using cmake
I get all the libraries built but at the end of the make I get

```
Linking CXX executable ale
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
     (maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mcmachado** [comment]
Hello,

we've spent a considerable amount of time trying to make sure CMake would properly find the correct path in different situations. However we realized that sometimes if the user has two installations (generally one via brew and another via dmg package), conflicts may arise. 

Generally it is enough to set the variable SDL_LIBRARY, in the CMake, as below (the most common path where SDL is installed is used here):

  SDL_LIBRARY:STRING=/usr/local/lib/libSDLmain.a;/usr/local/lib/libSDL.dylib;
  -framework Cocoa

This should work. Can you try that? I mean, verify if you have the SDL at this same path. Is is very likely that if you look at the CMakeCache you will see this variable with a wrong value. Then you compile it and it should work.

**Comment by udibr** [comment]
Thank you for answering so quickly, you were right on the spot!
I found the string you were talking about in CMakeCache.txt and indeed it was using an SDL framework (not brew) so instead of manually fixing it (in several locations in the file) I just removed the (old) SDL framework and re-run cmake from scratch and now everything is working! 
Excpet that now I have a new issue...
