### ISSUE TITLE
Allow game state serialization from C interface

### ISSUE THREAD

**Issue by Jragonmiris** [mgbellemare/Arcade-Learning-Environment#83]
At the moment, the C interface allows saving and loading of the game state onto an internal, opaque stack. It would be useful to be able to explicitly tell it to save/load a state from disk. 

I've been running UCT from an FFI wrapper, which can take several days, and it would be nice to be able to halt my program and restart my computer (or make it robust against power outages or whatever).

I'd guess this probably isn't much more complicated than saving the RAM query and a few small values like lives and score from the game-specific glue, but the wrapper lacks any real way to load this even if you can grab the values.

**Comment by mgbellemare** [comment]
This is actually easy to implement, since as you point out the save/load state process is already serializing nearly everything to a string. My recommendation is to add a pair of public methods to ALEState, `save(const char*)` and `load(const char*)` which write/read all of ALEState's private member variables to disk. Then you can do

    ALEState s = my_ale_interface.clone();
    s.save("/tmp/my_checkpoint");

**Comment by mgbellemare** [comment]
Also, see issue #70 and consider submitting the PR to the dev branch if possible.

**Comment by Jragonmiris** [comment]
Another idea, which I've implemented, is simply to serialize ALEState to a string. So you have (in ALEState):

    ALEState(std::string serialized);
    std::string encode();

The code for this is simple, it's just the fields of ALEState in declaration order separated by newlines. The parsing is just `getline` and `atoi` (`atoi` instead of `stoi` because unfortunately `stoi` doesn't exist on MinGW), with the final getline reading directly into the string field.

I prefer this to an explicit save to disk method because it allows wrappers from other languages to choose how to save the string -- naked file, with other structs in their own program, gzip it, etc. It's more compatible with other APIs.

**Comment by Jragonmiris** [comment]
The C interface would then just have an `char *aleStateEncode(ALEState *s);` and the reverse, which you can save/load with the new `saveSystemState` methods and such.

**Comment by mhauskn** [comment]
As a side note: I had attempted something similar to this when adding the current save/restore methods to the C interface. I had tried to return the ALEState::m_serialized_state as a char *, but found out that it quite often contains null terminators which resulted in char * being prematurely terminated.

**Comment by Jragonmiris** [comment]
This abuses a lot of C, but this code seems to work as long as you use the char * as a raw buffer of bytes instead of a c string:  http://cpp.sh/3hqc

**Comment by Jragonmiris** [comment]
Hmm, yeah, I think it messes up getline. That said, I can get it to work by treating the `char *` as a raw byte stream rather than a C String: http://cpp.sh/2u6di

**Comment by Jragonmiris** [comment]
I think I was too married to using `std::string` for some reason. It makes more sense to serialize into a `vector<char>` probably: http://cpp.sh/2fcdf

The C wrapper can still return a `char *`, with documentation that it's a byte buffer and not a string.

**Comment by mgbellemare** [comment]
Given that the Stella Serializer already produces a string in a way that handles null-terminated data, why not use the same to serialize everything?

**Comment by Jragonmiris** [comment]
Resolved by #109
