### ISSUE TITLE
Exception messages not printed out

### ISSUE THREAD

**Issue by mgbellemare** [mgbellemare/Arcade-Learning-Environment#85]
PR #82, #84 throw exceptions in response to fatal behaviour. Under Mac OS X exception messages are not printed out, resulting in cryptic errors. Consider implementing Logger::Fatal() which prints out the message and then throws the exception. Depends on #74.

**Comment by JesseFarebro** [comment]
Apple got around to fixing this. Exceptions are now printed on macOS.
