### ISSUE TITLE
Issue with SDL version detection

### ISSUE THREAD

**Issue by mhauskn** [mgbellemare/Arcade-Learning-Environment#99]
In some cases it seems that cmake is unable to detect the version of the SDL library that is installed, leading to issues in the build process as described here:

https://groups.google.com/forum/#!topic/arcade-learning-environment/-PnnqTg35HM

CMakeLists.txt (https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/CMakeLists.txt#L21) poses issues when SDL version is not detected.

**Comment by JesseFarebro** [comment]
For anyone who comes upon this: this shouldn't be an issue with modern versions of CMake + the SDL2 upgrade (#368). Also, we'd recommend using [vcpkg](https://vcpkg.io/en/index.html) to manage dependencies.
